server.port=${SERVER_PORT:8081}

spring.application.name=workflow-service
configuration.service.url=${CONFIGURATION_SERVICE_URL:http://configuration.internal.services:8080}
matching.service.url=${MATCHING_SERVICE_URL:http://matching.internal.services:8081}
aws.sqs.workflow-request-queue-name=${AWS_SQS_WORKFLOW_REQUEST_QUEUE_NAME:}
dynamodb.table.name=${DYNAMODB_TABLE_NAME:workflow-reviews}
