package com.fh_wedel.notification.model;

import com.fh_wedel.notification.config.UuidAttributeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondarySortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

import java.time.Instant;
import java.util.UUID;

/**
 * DynamoDB entity representing a single in-app notification for a user.
 * <p>
 * Table schema (single-table design):
 * <ul>
 *   <li>PK: {@code NOTIFICATION#{id}}</li>
 *   <li>SK: {@code META}</li>
 * </ul>
 * GSI "UserIndex" (lists a user's notifications newest-first):
 * <ul>
 *   <li>GSI-PK: {@code userSub}</li>
 *   <li>GSI-SK: {@code createdAt}</li>
 * </ul>
 * The {@code pk}/{@code sk} attributes are derived from {@code id} and are
 * populated by the repository before persisting.
 * <p>
 * The Enhanced Client reads its schema from the getters, so the key/index/
 * converter getters are written explicitly (Lombok skips already-defined
 * accessors); the remaining accessors, the builder and the no-arg constructor
 * are generated by Lombok.
 */
@DynamoDbBean
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InAppNotification {

    public static final String PK_PREFIX = "NOTIFICATION#";
    public static final String SK_VALUE = "META";
    public static final String USER_INDEX = "UserIndex";

    private String pk;

    private String sk;

    private UUID id;

    private String userSub;

    private String title;

    private String body;

    @Builder.Default
    private boolean read = false;

    @Builder.Default
    private Instant createdAt = Instant.now();

    @DynamoDbPartitionKey
    public String getPk() {
        return pk;
    }

    @DynamoDbSortKey
    public String getSk() {
        return sk;
    }

    @DynamoDbConvertedBy(UuidAttributeConverter.class)
    public UUID getId() {
        return id;
    }

    @DynamoDbSecondaryPartitionKey(indexNames = USER_INDEX)
    public String getUserSub() {
        return userSub;
    }

    @DynamoDbSecondarySortKey(indexNames = USER_INDEX)
    public Instant getCreatedAt() {
        return createdAt;
    }
}
