package com.fh_wedel.notification.model;

import com.fh_wedel.notification.config.ChannelTypeConverter;
import com.fh_wedel.notification.config.NotificationStatusConverter;
import com.fh_wedel.notification.config.UuidAttributeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondarySortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

import java.time.Instant;
import java.util.UUID;

/**
 * DynamoDB entity recording a single notification dispatch attempt.
 * <p>
 * Table schema (single-table design):
 * <ul>
 *   <li>PK: {@code LOG#{id}}</li>
 *   <li>SK: {@code META}</li>
 * </ul>
 * GSI "StatusIndex" (sparse — only log items carry a {@code status}):
 * <ul>
 *   <li>GSI-PK: {@code status}</li>
 *   <li>GSI-SK: {@code createdAt}</li>
 * </ul>
 * The {@code pk}/{@code sk} attributes are derived from {@code id} and are
 * populated by the repository before persisting.
 * <p>
 * The Enhanced Client reads its schema from the getters, so the key/index/
 * converter getters are written explicitly (Lombok skips already-defined
 * accessors); the remaining accessors, the builder and the no-arg constructor
 * are generated by Lombok.
 */
@DynamoDbBean
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class NotificationLog {

    public static final String PK_PREFIX = "LOG#";
    public static final String SK_VALUE = "META";
    public static final String STATUS_INDEX = "StatusIndex";

    private String pk;

    private String sk;

    private UUID id;

    private ChannelType channel;

    private String recipient;

    private String subject;

    private String body;

    @Builder.Default
    private NotificationStatus status = NotificationStatus.PENDING;

    private String errorMessage;

    @Builder.Default
    private Instant createdAt = Instant.now();

    private Instant sentAt;

    @DynamoDbPartitionKey
    public String getPk() {
        return pk;
    }

    @DynamoDbSortKey
    public String getSk() {
        return sk;
    }

    @DynamoDbConvertedBy(UuidAttributeConverter.class)
    public UUID getId() {
        return id;
    }

    @DynamoDbConvertedBy(ChannelTypeConverter.class)
    public ChannelType getChannel() {
        return channel;
    }

    @DynamoDbConvertedBy(NotificationStatusConverter.class)
    @DynamoDbSecondaryPartitionKey(indexNames = STATUS_INDEX)
    public NotificationStatus getStatus() {
        return status;
    }

    @DynamoDbSecondarySortKey(indexNames = STATUS_INDEX)
    public Instant getCreatedAt() {
        return createdAt;
    }
}
