package com.fh_wedel.response.model;

import com.fh_wedel.response.config.UuidAttributeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondarySortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * DynamoDB entity representing the result of a completed review for a submission.
 * <p>
 * Table schema (single-table design):
 * <ul>
 *   <li>PK: {@code SUBMISSION#{submissionId}}</li>
 *   <li>SK: {@code RESULT#{reviewerId}}</li>
 * </ul>
 * GSI "AuthorIndex" (lists all results that belong to an author):
 * <ul>
 *   <li>GSI-PK: {@code authorId}</li>
 *   <li>GSI-SK: {@code submissionId}</li>
 * </ul>
 * The {@code pk}/{@code sk} attributes are derived from {@code submissionId} and
 * are populated by the repository before persisting.
 * <p>
 * The Enhanced Client reads its schema from the getters, so the key/index/
 * converter getters are written explicitly (Lombok skips already-defined
 * accessors); the remaining accessors, the builder and the no-arg constructor
 * are generated by Lombok.
 */
@DynamoDbBean
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ReviewResult {

    public static final String PK_PREFIX = "SUBMISSION#";
    public static final String SK_VALUE = "RESULT";
    public static final String AUTHOR_INDEX = "AuthorIndex";

    private String pk;

    private String sk;

    private UUID id;

    private String submissionId;

    private String reviewerId;

    private String authorId;

    private String finalGrade;

    private String reviewComments;

    private String documentS3Key;

    /** Usernames of the examiners who reviewed the submission (from the matching service). */
    private List<String> examinerUsernames;

    /** Review deadline / end date for the submission (from the configuration service). */
    private Instant reviewDeadline;

    /** Grading schema the submission was reviewed by (snapshot from the workflow service). */
    private List<GradingCriterion> gradingSchema;

    private List<ReviewAnswer> answers;

    private Instant completedAt;

    @Builder.Default
    private Instant createdAt = Instant.now();

    @DynamoDbPartitionKey
    public String getPk() {
        return pk;
    }

    @DynamoDbSortKey
    public String getSk() {
        return sk;
    }

    @DynamoDbConvertedBy(UuidAttributeConverter.class)
    public UUID getId() {
        return id;
    }

    @DynamoDbSecondaryPartitionKey(indexNames = AUTHOR_INDEX)
    public String getAuthorId() {
        return authorId;
    }

    @DynamoDbSecondarySortKey(indexNames = AUTHOR_INDEX)
    public String getSubmissionId() {
        return submissionId;
    }
}
