spring.application.name=submission
spring.main.banner-mode=off
management.endpoint.health.probes.enabled=true
server.port=${SERVER_PORT:8081}

# AWS SQS Configuration
spring.cloud.aws.sqs.dualstack-enabled=true
aws.sqs.request.queue-name=${SQS_REQUEST_QUEUE:submission-request-queue}
aws.sqs.workflow.queue-name=${SQS_WORKFLOW_QUEUE:workflow-request-queue}
aws.sqs.notification.queue-name=${SQS_NOTIFICATION_QUEUE:}
spring.cloud.aws.region.static=${AWS_REGION:eu-north-1}

# DynamoDB Configuration
aws.dynamodb.table-name=${DYNAMODB_TABLE_NAME:submission-service-table}
spring.cloud.aws.dynamodb.dualstack-enabled=true

# S3 Configuration
aws.s3.bucket-name=${S3_BUCKET_NAME:peerreview-submissions-bucket}

# Configuration Service (internal ECS-to-ECS)
services.configuration.url=${CONFIGURATION_SERVICE_URL:http://configuration.internal.services:8080}
