spring.application.name=configuration
spring.main.banner-mode=off
management.endpoint.health.probes.enabled=true
server.port=${SERVER_PORT:8080}

# AWS SQS Configuration
spring.cloud.aws.sqs.dualstack-enabled=true
aws.sqs.matching-request-queue-name=${SQS_MATCHING_REQUEST_QUEUE:matching-request-queue}
aws.sqs.notification-queue-name=${SQS_NOTIFICATION_QUEUE:}
aws.sqs.cache-invalidation-queue-name=${SQS_CACHE_INVALIDATION_QUEUE:user-cache-invalidation-queue}
spring.cloud.aws.region.static=${AWS_REGION:eu-north-1}

# DynamoDB Configuration
aws.dynamodb.table-name=${DYNAMODB_TABLE_NAME:configuration-service-configs}
spring.cloud.aws.dynamodb.dualstack-enabled=true
# Plugin Architecture
configuration.plugins.directory=${PLUGINS_DIRECTORY:/app/plugins}
