// Add Numbering of headings
#set heading(numbering: "1.1")
#import "@preview/glossarium:0.5.10": gls, glspl

= Architekturentwurf <ch:architecture>
Einen Kernpunkt dieser Ausarbeitung bildet die zugrunde liegende Softwarearchitektur. Um eine ausfallsichere und skalierbare Software zu entwickeln, fanden durchgehend moderne Architekturmuster Anwendung. Diese Muster wurden auf allen Ebenen des Systems berücksichtigt, von der grundlegenden Klassifizierung als Microservices-Architektur bis hin zur Nutzung spezifischer Webprotokolle wie @SSE für die asynchrone Kommunikation. Im Folgenden werden die verschiedenen Architekturebenen detailliert dargestellt sowie die zugrunde liegenden Motivationen und die daraus resultierenden technischen Einschränkungen beleuchtet.

== Übersicht <sec:overview>
Die entwickelte Software implementiert eine Microservices-Architektur, bei der domänenspezifische Fachlichkeiten nach dem Prinzip der losen Kopplung gekapselt und in eigenständige Services ausgelagert wurden. Grundlage hierfür war eine detaillierte Analyse des gesamten Peer-Review-Prozesses, aus der sich spezifische fachliche Schwerpunkte (Bounded Contexts) ableiten ließen.

Insgesamt wurden acht Domänen identifiziert. @fig:application-architecture bietet einen Überblick über alle Services sowie deren Relationen zueinander. Vier dieser Services bilden das Kern-Framework des eigentlichen Review-Prozesses, während vier weitere Services zusätzliche allgemeine oder technisch bedingte Domänen abdecken.

Die Services des Frameworks umfassen den Configuration Service, Matching Service, Submission Service und Response Service. Die Architektur des Erstgenannten wird im nachfolgenden @sec:configuration-service genau erläutert. Grundsätzlich besteht dessen Fachlichkeit darin, verschiedene Einreichungstypen sowie Review-Formate bereitzustellen und das Erstellen neuer Abgaben zu verwalten. Nach dem erfolgreichen Anlegen einer Abgabe ermittelt der Matching Service eine passende Kombination aus Abgabe und Reviewer, wobei die allgemeine Verfügbarkeit sowie die jeweiligen Fachgebiete berücksichtigt werden. Anschließend ermöglicht der Submission Service die eigentliche Abgabe der Arbeit durch den Autor mittels eines Uploads im Format PDF. Abschließend nimmt der Response Service die Gutachten der Reviewer entgegen und stellt diese nach Abschluss des gesamten Prozesses dem Autor zur Verfügung.

#set figure.caption(position: bottom)

#figure(
  image("../bilder/Architecture High Level.drawio.pdf", width: 100%),
  caption: [Applikationsarchitektur],
) <fig:application-architecture>

Auffällig ist der Verzicht auf einen zentralen Orchestrierungs-Service (Orchestrator), welcher in Microservices-Architekturen häufig zum Einsatz kommt. Diese Entscheidung wird durch die Natur des Peer-Review-Verfahrens begünstigt: Es handelt sich um einen deterministischen Workflow, bei dem nach jedem abgeschlossenen Schritt eindeutig der nächste folgt. Die einzelnen Services des Frameworks können somit über eine ereignisgesteuerte Architektur (Event-Driven Architecture) mittels asynchroner Message-Queues direkt miteinander kommunizieren.

Die zusätzlichen Services umfassen den Communication Service, Notification Service, User Service sowie die Web-UI. Der Communication Service ermöglicht den interaktiven Austausch der Nutzer über die Plattform, entweder in Form von Direktnachrichten zwischen zwei Personen oder als fachlicher Austausch über eine spezifische Abgabe mit mehreren Beteiligten. Diese Funktion berücksichtigt strikt die Vorgaben des Configuration Service, der je nach Review-Format (z. B. Double-Blind-Verfahren) jegliche direkte Kommunikation unterbinden kann. Der Notification Service ist für die Benachrichtigung der Nutzer verantwortlich. Diese Benachrichtigungen werden vom System basierend auf spezifischen Ereignissen im Review-Prozess generiert und dem Anwender asynchron ausgespielt. Details dazu, wie die Software verschiedene Benachrichtigungskanäle bereitstellen kann, werden in @sec:strategy-pattern erläutert. Der User Service bietet eine einheitliche Schnittstelle für das @IAM, wobei dieser Service eine Abstraktionsschicht („Wrapper“) für Cognito auf @AWS darstellt, was im @sec:user-management detailliert beschrieben wird. Die Web-UI bündelt die Schnittstellen der Backend-Services für den Endnutzer und wird in @sec:frontend weiter erläutert.

Die technologische Basis bilden im Backend Java 25 mit dem Spring Boot Framework sowie React mit Vite für das Frontend. Die Infrastruktur wird vollständig über @AWS abgebildet und im @sec:infra-architecture näher beleuchtet. Der gewählte Microservices-Ansatz erlaubt prinzipiell eine polyglotte Entwicklung, bei der beliebige Technologien eingesetzt werden können, sofern die Schnittstellen zur Anwendungsprogrammierung (API) kompatibel bleiben. Zu diesem Zweck stellen alle Backend-Services ihre Funktionalitäten über vollständig dokumentierte Schnittstellen gemäß REST auf Basis von Spezifikationen gemäß OpenAPI bereit.

Die Backend-Services lassen sich als funktionale Basis-Services kategorisieren. Sie umfassen bewusst eng gefasste Fachlichkeiten und bilden isoliert betrachtet keinen eigenständigen, vollständigen Geschäftsprozess ab. Erst durch die Integration in der zustandslosen Web-UI, die als aggregierender Service agiert, verschmelzen die isolierten Schnittstellen zur Anwendungsprogrammierung zu einem zusammenhängenden Prozess. Dieser Ansatz der clientseitigen Bündelung bietet den Architekturvorteil, dass die Web-UI hochgradig austauschbar ist. Es können jederzeit neue Frontends entwickelt werden, die basierend auf den vorhandenen Schnittstellen gemäß REST einen modifizierten Detaillierungsgrad oder alternative User Journeys abbilden, ohne die Backend-Logik anzupassen.

== Infrastruktur Architektur <sec:infra-architecture>
Die Architektur basiert auf containerisierten Deployments der einzelnen Microservices. Die gesamte Bereitstellung der Compute-Ressourcen sowie weiterer Plattform-Dienste erfolgt über @AWS. Es ist aus architektonischer Sicht kritisch anzumerken, dass die tiefe Integration proprietärer @AWS\-Services das Risiko eines Vendor-Lock-ins birgt, was für einen dauerhaften Produktivbetrieb sorgfältig evaluiert werden müsste. Im Rahmen dieser Arbeit entsprach ein Deployment in @AWS sowie die exklusive Bindung an das entsprechende Ökosystem jedoch den expliziten Vorgaben der Aufgabenstellung und der durch die Hochschule bereitgestellten Infrastruktur.

Ein maßgebliches Entwurfskriterium war eine strikte Kosteneffizienz, weshalb ausschließlich moderne Serverless-Komponenten zum Einsatz kommen. Zugunsten der Kostenoptimierung wurde auf eine ausgedehnte High-Availability-Architektur mit @multi-az vorerst verzichtet, eine nachträgliche Implementierung ist jedoch möglich und vorbereitet.

@fig:infra-architecture veranschaulicht die eingesetzten Dienste von @AWS sowie deren strukturelles Zusammenwirken innerhalb der Software. Die genaue Funktionsweise dieser Komponenten wird in den nachfolgenden Abschnitten detailliert beschrieben.

#set figure.caption(position: bottom)

#figure(
  image("../bilder/Infra Architecture High Level-AWS.drawio.pdf", width: 100%),
  caption: [Infrastrukturarchitektur (@AWS)],
) <fig:infra-architecture>

=== Compute <sec:compute>
Die Bereitstellung der Rechenleistung (Compute) erfolgt über @ECS in Kombination mit der Serverless-Compute-Engine Fargate auf @AWS. Fargate ermöglicht die vollautomatisierte Provisionierung von Laufzeitumgebungen für Docker-Container, deren Images in @ECR versioniert vorliegen.

Die Ausfallsicherheit der Services ist systembedingt hoch und kann durch vertikales Skalieren weiter optimiert werden. Zur Bewältigung von Lastspitzen kommt ein Autoscaler zum Einsatz, der mittels einer Target-Tracking-Skalierungsrichtlinie (Target Tracking Policy) eine durchschnittliche Auslastung der CPU von 75 % anstrebt. Bei Überschreiten dieses Schwellenwerts wird vertikal hochskaliert, bei geringerer Last entsprechend herunterskaliert. Auch das kontinuierliche Ausrollen neuer Software-Versionen wird durch Fargate auf @ECS nativ unterstützt, was moderne Deployment-Strategien wie Blue/Green-, Canary- oder Rolling-Deployments ermöglicht. Aktuell wird das Rolling-Deployment verwendet, wobei neue Service-Instanzen parallel gestartet werden und erst nach erfolgreicher Gesundheitsprüfung (Health Check) für den produktiven Datenverkehr freigegeben. Die alten Instanzen werden vollautomatisch deprovisioniert.

Zur weiteren Kostenreduktion nutzen alle auf @ECS bereitgestellten Services eine Prozessorarchitektur gemäß ARM64 (Graviton von @AWS), welche ein besseres Preis-Leistungs-Verhältnis aufweist als vergleichbare x86-Architekturen. Zudem werden Spot-Instanzen von @AWS verwendet, die erhebliche Rabatte bieten, jedoch bei Kapazitätsengpässen kurzfristig terminiert werden können. Für den aktuellen Projektstatus ist dies ein idealer Kompromiss, da kurze Downtimes tolerierbar sind und der Autoscaler ausfallende Instanzen automatisch durch neue ersetzt. Für einen ausfallsicheren Produktivbetrieb könnte das System auf eine Strategie mit @multi-az erweitert werden, um den Ausfall einzelner Rechenzentren transparent zu kompensieren. Aufgrund der damit verbundenen Mehrkosten wurde dies jedoch im aktuellen Scope nicht umgesetzt.

Da jede Instanz mit der kleinstmöglichen Konfiguration von 0,256 vCPUs und 512 MB RAM dimensioniert ist, belaufen sich die reinen Compute-Kosten, unter der Annahme, dass kein Autoscaling stattfindet und kontinuierlich nur eine Instanz läuft, auf 0,078192 € pro Tag. In Summe resultiert dies in Kosten von 0,625536 € pro Tag für alle Services, was die Vorgabe einer hocheffizienten Infrastruktur vollumfänglich erfüllt.

Die Compute-Instanzen kommunizieren größtenteils asynchron und entkoppelt über @SQS. Hierbei wurde das Paradigma der Data Ownership strikt angewendet: Jeder Service stellt eine dedizierte Queue von @SQS als Eingangskanal (Input Queue) bereit. Andere Services, die Daten an diesen Service übergeben möchten, schreiben ihre Events direkt in die jeweilige Ziel-Queue.

Bestimmte fachliche Abläufe erfordern jedoch eine synchrone Kommunikation, welche direkt über REST abgebildet wurde. Dafür nutzen die Services interne Namen des DNS zur Service Discovery über CloudMap, deren Funktionsweise im folgenden Abschnitt zum Netzwerk erläutert wird.

=== Netzwerk <sec:network>
Netzwerkseitig wird die Software in einer @VPC überwiegend in einem sicheren, privaten Subnetz bereitgestellt. Die Netzwerkkonfiguration ist ein kritischer Aspekt der Kostenoptimierung, da insbesondere passiv bereitgestellte Netzwerkinfrastruktur in der Cloud von @AWS erhebliche Fixkosten verursachen kann.

Durch das Deployment in ein privates Subnetz sind die Instanzen nicht über das öffentliche Internet routingfähig, was die Sicherheit der Architektur signifikant erhöht. Dies bedeutet jedoch auch, dass die auf @ECS bereitgestellten Instanzen ohne weitere Maßnahmen nicht nach außen kommunizieren können, um beispielsweise initiale Docker-Images aus @ECR zu pullen. Ein klassischer Lösungsansatz bestünde in der Provisionierung eines von @AWS verwalteten @NAT Gateway. Ein @NAT Gateway verursacht jedoch hohe passive Kosten von ca. 50 € pro Monat, zuzüglich variabler Traffic-Kosten. Eine Alternative wäre die Zuweisung öffentlicher Adressen nach IPv4 an jede Instanz auf @ECS. Da @AWS jedoch Gebühren für die Nutzung öffentlicher Adressen nach IPv4 erhebt (ca. 3,50 € pro IP/Monat), würden sich die monatlichen Kosten bei acht Services auf knapp 30 € summieren.

Die implementierte Lösung nutzt stattdessen ein reines Netzwerk auf Basis von IPv6. @AWS ermöglicht es, einem Subnetz auf Basis von IPv6 ein kostenfreies Egress-Only-Internet-Gateway zuzuordnen. Dadurch können die Instanzen auf @ECS ausgehende Verbindungen über IPv6 aufbauen, um Abhängigkeiten oder Images aus @ECR herunterzuladen. Obwohl @AWS auch Dual-Stack-Subnetze (parallele Nutzung von IPv4 und IPv6) anbietet, war dieser Ansatz nicht zielführend. In einem Dual-Stack-Setup nutzen Instanzen auf @ECS den Image-Pull über IPv4, was ohne @NAT Gateway oder öffentliche Adresse nach IPv4 zwangsläufig fehlschlägt. Der konsequente Einsatz eines reinen Subnetzes auf Basis von IPv6 löst dieses Problem kostenneutral, schafft jedoch neue Herausforderungen beim Routing des eingehenden Datenverkehrs (Ingress).

Externe Requests müssen die Instanzen auf @ECS erreichen, optimalerweise nicht über Adressen nach IPv6, sondern über DNS. Hierfür kommt das API Gateway von @AWS zum Einsatz, das eine öffentlich verfügbare Auflösung über DNS ohne Fixkosten bereitstellt. Die technische Limitierung besteht jedoch darin, dass das API Gateway Instanzen auf @ECS in einem reinen Netzwerk auf Basis von IPv6 nicht direkt als Ziel (Target) adressieren kann, da es zwingend Endpunkte nach IPv4 erwartet. Als Lösung wurden Lambda-Funktionen von @AWS als Proxy-Schicht entwickelt und in einem separaten, Dual-Stack-fähigen Subnetz bereitgestellt. Das API Gateway routet eingehende Anfragen an diese Lambda-Proxies, welche die Requests an die Services auf @ECS im Subnetz auf Basis von IPv6 weiterleiten. Die Lambdas können in einem Dual-Stack-Subnetz betrieben werden, da sie keine externen Docker-Images über IPv4 beziehen müssen und die Netzwerkstrecke nach IPv4 zum API Gateway systemseitig gewährleistet ist.

Für dieses Proxy-Pattern müssen die Lambda-Funktionen die internen, dynamischen Adressen nach IPv6 der Services auf @ECS kennen. Zur Realisierung der Service Discovery kommt Cloud Map von @AWS zum Einsatz. Alle Services auf @ECS registrieren sich beim Bootvorgang vollautomatisch bei Cloud Map. Die Lambda-Proxies fragen den internen Namen des DNS über Cloud Map ab, erhalten die aktuelle Adresse nach IPv6 des Ziels und leiten den Request entsprechend weiter.

Dieser Lambda-Proxy-Ansatz kann durch sogenannte Kaltstarts (Cold Starts) zeitweise zu erhöhten Latenzen führen, da die Initialisierung der Lambda-Laufzeitumgebung einige Sekunden beanspruchen kann. Eine performantere, aber kostenintensive Lösung ist die Nutzung von Provisioned Concurrency, bei der vorkonfigurierte Lambda-Instanzen warmgehalten werden. Diese Funktion wird im Projekt jedoch nur temporär zu Demonstrations- und Testzwecken aktiviert. Alternativ ließe sich ein @ALB implementieren, der die Lambda-Proxies oder gar das API Gateway ersetzt, eine feste Adresse nach IPv4 bereitstellt und Lastverteilungs-Metriken nativ unterstützt. Die fixen Vorhaltekosten eines @ALB belaufen sich jedoch auf ca. 16 € pro Monat. Bei einer dedizierten Bereitstellung pro Service würden somit monatliche Fixkosten von rund 130 € entstehen, was den ökonomischen Vorgaben des Projekts widerspricht.

Ein weiterer Lambda-Proxy wurde zwischen dem Response Service und Bedrock von @AWS implementiert, da Bedrock derzeit keine nativen Verbindungen über IPv6 unterstützt. Durch das Proxying über eine Dual-Stack-fähige Lambda-Funktion konnte diese Einschränkung erfolgreich umgangen werden.

Den Abschluss der Netzwerkarchitektur bildet CloudFront von @AWS als @CDN. CloudFront reduziert die globale Latenz durch Edge-Caching und leitet Anfragen effizient an den geografisch nächsten Edge-Standort weiter. Über CloudFront wurde zudem die Custom Domain `fh-wedel.dev` konfiguriert. Anstatt die flüchtigen Endpunkte des API Gateways direkt anzusprechen, ermöglicht Route 53 von @AWS eine feste Auflösung über DNS, sodass externe Anfragen konsistent über die Custom Domain an das API Gateway geroutet werden.

=== Datenbank Architektur <sec:database-architecture>
Die Datenbankarchitektur unterliegt denselben strengen Vorgaben zur Kosteneffizienz. Es war zwingend erforderlich, eine vollständig serverlose Datenbanklösung ohne Fixkosten zu implementieren. Da die Geschäftsdaten keine strenge relationale Modellierung erforderten, fiel die Wahl auf DynamoDB von @AWS, eine hochskalierbare Key-Value-Datenbank mit einem Pay-per-Request-Preismodell.

Um eine starke strukturelle Kopplung zu vermeiden und die Unabhängigkeit der Microservices zu wahren, wurde das Database-per-Service-Pattern konsequent umgesetzt. Jeder Service, der Persistenz benötigt, verfügt über eine eigene, isolierte DynamoDB-Tabelle.

Bei der Datenmodellierung kam konsequent ein modernes Single-Table-Design zum Einsatz. Dieser Ansatz ermöglicht es, alle zu einer Abgabe gehörenden Entitäten eines Services über eine einzige Query hocheffizient abzufragen. Komplizierte Joins über mehrere Tabellen hinweg oder das Absetzen sequenzieller Abfragen (N+1-Problem) entfallen dadurch vollständig.

Zudem wird das Prinzip der Datenhoheit (Data Sovereignty) strikt eingehalten: Jeder Service speichert ausschließlich die Daten, die in seinen Bounded Context fallen. Dies verhindert Datenredundanz über mehrere Services hinweg und eliminiert das Risiko von Dateninkonsistenzen bei Updates. Benötigt ein Service aggregierte Daten, fragt er diese zur Laufzeit über die REST-Schnittstelle des zuständigen Data Owners an.

=== User Management <sec:user-management>
Für das @IAM werden Cognito von @AWS und @AVP genutzt. Cognito agiert als Managed IdP und übernimmt komplexe Aufgaben wie die Bereitstellung gehosteter Login-Seiten, das Management von Anmeldeinformationen (Credentials) sowie die Verwaltung von Session-Tokens. Dies entspricht Best Practices der modernen Softwareentwicklung, da sich das Entwicklungsteam auf die Kernkompetenzen und die Geschäftslogik konzentrieren kann. Zudem ermöglicht Cognito die Gruppierung von Nutzern, was die Grundlage für eine rollenbasierte Zugriffskontrolle (@RBAC) bildet.

Zur Autorisierung der Endpunkte des API Gateways kommt @AVP zum Einsatz. @AVP definiert feingranulare Policies, die den Zugriff auf Ressourcen regulieren, sodass nur berechtigte Cognito-Benutzergruppen bestimmte Endpunkte der API aufrufen dürfen. Die Durchsetzung dieser Richtlinien erfolgt über einen Lambda Authorizer, der vom API Gateway bei jedem eingehenden Request aufgerufen wird. Diese Lambda-Funktion validiert das Session-Token, gleicht die Cognito-Gruppen des Nutzers mit den in @AVP hinterlegten Policies ab und trifft die finale Autorisierungsentscheidung (Allow/Deny).

Auch diese Architektur erzeugt keine passiven Kosten, und die nutzungsbasierten Gebühren für Cognito und @AVP sind marginal. Der einzige Trade-off besteht in potenziellen Latenzen durch Kaltstarts des Lambda Authorizers. Auch hier kann durch Provisioned Concurrency die Antwortzeit signifikant optimiert werden, ein Effekt, der sich potenziert, wenn parallel auch der Lambda-Proxy vorkonfiguriert ist.

Zusätzliche Sicherheitsmechanismen sind direkt in der Geschäftslogik (Applikationsschicht) verankert. Hierbei entscheidet die Software kontextbezogen, ob ein Nutzer bestimmte Datensätze lesen oder mutieren darf (z. B. Author einer Abgabe). Diese Logik wird über Spring Security abgebildet, wobei die aus Cognito von @AWS injizierten Benutzernamen und Rollen als vertrauenswürdige Quelle (Single Source of Truth) dienen.

== Configuration Service (Plugin Service) <sec:configuration-service>
// Luca

Die Aufgabe des Configuration Service besteht darin, die Erstellung neuer Review-Abgaben zu verwalten und die hierbei verfügbaren Konfigurationsmöglichkeiten zur Abfrage bereitzustellen. Hierfür unterstützt der Service Plugins, welche es erlauben neue Review-Typen (z. B. Einfachblind oder Doppelblind) und -Formate zu definieren (z. B. Gruppenarbeit oder Bachelor Thesis). Hierdurch können beispielsweise unterschiedliche Bewertungskriterien in Abhängigkeit vom Review-Format spezifiziert werden. Der Service lädt die bereitgestellten Plugins beim Starten der Anwendung dynamisch, wodurch es nicht erforderlich ist, den Service bei der Einführung neuer Plugins neu zu bauen.

Der Service stellt diverse REST-Endpunkte zur Verfügung, über die das Frontend beim initialen Aufruf der PeerReview-Webseite unter anderem die verfügbaren Plugins ermittelt. Sobald dies geschehen ist, kann der Nutzer eine neue Abgabe erstellen, wobei der Titel der Arbeit, die Autoren, die zugehörige Fachrichtung sowie der Review-Typ und das Review-Format spezifiziert werden muss. In Abhängigkeit von der Rolle des Nutzers (z. B. Author, Teacher oder Admin) können auch weitere optionale Parameter wie die Abgabefrist oder vorgegebene Reviewer ausgewählt werden. Sobald die Abgabe beim Configuration Service eingereicht wurde, validiert der Service die Eingaben und speichert die Abgabe in einer DynamoDB-Tabelle. Anschließend wird ein Event in die #gls("SQS")-Queue vom Matching Service geschrieben, um den nächsten Schritt im Review-Prozess einzuleiten.

Im Rahmen des @MVP wurde der Configuration Service mit insgesamt acht Plugins ausgestattet. Drei Plugins definieren die Review-Typen (Einfachblind, Doppelblind und Offen) und fünf weitere Plugins spezifizieren die Review-Formate (Einzelarbeit, Gruppenarbeit, Bachelor Thesis, Master Thesis und Seminararbeit). Die Erstellung neuer Plugins ist einfach und erfordert lediglich die Implementierung eines Plugin Interfaces, woraufhin die daraus resultierende Archivdatei im Format JAR in das Plugin-Verzeichnis des Configuration Service kopiert oder eingebunden werden muss.

== @SSE im Communication und Notification Service <sec:sse-communication>
Eine architektonische Besonderheit des Communication und Notification Services ist die Implementierung von @SSE. @SSE etabliert eine unidirektionale Verbindung vom Server zum Client, über die der Server asynchron Live-Updates und Benachrichtigungen pushen kann. Im Vergleich zu WebSockets, die bidirektional und in der Handhabung deutlich komplexer sind, stellt @SSE für diesen Anwendungsfall eine leichtgewichtigere Alternative dar. Auch gegenüber clientseitigem Polling (z. B. Short oder Long Polling) bietet @SSE den Vorteil, dass Updates in Echtzeit und mit stark reduziertem Overhead (ohne ständigen Verbindungsaufbau) übertragen werden.

Der Einsatz von @SSE hat sich für die Chat- und Benachrichtigungsfunktionen als äußerst zuverlässig erwiesen. Es existiert jedoch eine signifikante infrastrukturelle Einschränkung durch das API Gateway von @AWS, welches ein hartes Timeout von 29 Sekunden für aktive Verbindungen erzwingt. Für eine langlebige Verbindung über @SSE ist dies im Standardbetrieb nicht praktikabel.

Um dieses Limit zu umgehen, beendet der Server die Verbindung über @SSE proaktiv nach 25 Sekunden. Da das Protokoll @SSE nativ über Selbstheilungsmechanismen (Auto-Reconnect) verfügt, erkennt der Client den Verbindungsabbruch sofort und baut die Verbindung automatisch neu auf. Dadurch wird ein scheinbar unterbrechungsfreier Live-Datenstrom simuliert.

== Strategy Pattern im Notification Service <sec:strategy-pattern>

Der Notification Service verwendet das Strategy Pattern, um die verschiedenen Versandkanäle von der eigentlichen Zustellung zu entkoppeln. Jeder Kanal implementiert das gemeinsame Interface `NotificationChannel`; der `NotificationDispatcher` wählt anhand des angeforderten Kanaltyps die passende Strategie aus und führt deren Versand aus. Aktuell existieren Strategien für In-App-Benachrichtigungen, E-Mail, Slack und Discord. Dadurch bleiben die aufrufenden Services von kanalspezifischen Details wie @SSE, SMTP oder Webhooks unabhängig, während Versandversuche einheitlich protokolliert werden. Im @MVP können Nutzer über die Web-UI jedoch noch keine zusätzlichen Empfänger oder externe Kanäle individuell konfigurieren. Künftig sollten solche Präferenzen über die Benutzeroberfläche verwaltet und beim Erzeugen der Benachrichtigung berücksichtigt werden. Weitere Versandwege lassen sich dann durch eine zusätzliche Strategie ergänzen, ohne den Dispatcher anzupassen.

== Web-UI <sec:frontend>
// Luca -- (Gideon)

Der Service der Web-UI ist für die Bereitstellung der Weboberfläche des PeerReview-Systems verantwortlich. Sie nimmt in der komponenten- und ereignisgesteuerten Gesamtanwendung eine zentrale Rolle ein, da sie zur Ermöglichung von Benutzerinteraktionen Daten bereitstellen muss, welche auf diverse Services verteilt vorliegen. Hierdurch wird einerseits die Skalierung von einzelnen Services ermöglicht, andererseits wird jedoch gleichzeitig eine Datenaggregation erforderlich, bevor die Weboberfläche vollständig angezeigt werden kann. Angesichts des Umfangs des Projekts wurde sich in diesem Zusammenhang dazu entschieden, kein dediziertes @BFF zu implementieren, welches diese Aufgabe übernehmen könnte. Folglich obliegt es der Web-UI, die notwendigen Daten von den verschiedenen Services abzurufen und zusammenzuführen. Dies soll dazu beitragen, die Weboberfläche weiter zu entkoppeln und infrastrukturelle Komplexität gemäß der Idee zur Implementierung eines @MVP zu reduzieren. Die Weboberfläche ist zustandslos und verwendet hiervon abweichend lediglich den LocalStorage des Browsers, um Einstellungen wie den präferierten Ansichtsmodus des Benutzers zu speichern. Konzeptionell erklärt sich aus diesen Bedingungen, weshalb die Weboberfläche als @SPA unter Verwendung von React und Vite implementiert wurde. Dies ermöglicht es, Daten von verschiedenen Services asynchron abzurufen und die Benutzeroberfläche dynamisch und schrittweise zu aktualisieren, ohne dass eine vollständige Seitenaktualisierung erforderlich wird. Die zusätzliche Verwendung eines @CDN erlaubt es zudem, die Latenzzeit der Weboberfläche zu reduzieren.

Zur Kommunikation mit den Backend-Services werden von der Web-UI ausschließlich Clients verwendet, welche anhand der Spezifikationen gemäß OpenAPI der jeweiligen Services automatisiert generiert wurden. Der Aufbau des Projekts als Mono-Repository trägt hierbei dazu bei, dass die Schnittstellen leicht überprüfbar bleiben und inkompatible Änderungen frühzeitig bemerkt werden. Anpassungen an einem Service erfordern lediglich die Neugenerierung des jeweiligen Clients. In diesem Zuge wurde auf die explizite Einführung von Data-Access-Objekten innerhalb der Weboberfläche verzichtet. Sollte die Komplexität des Projekts durch zukünftige Erweiterungen steigen oder externe Services angebunden werden, sollte dies erneut evaluiert werden.

Die Weboberfläche ist aufgrund der Verwendung von @AWS Cognito nicht für die Bereitstellung einer Anmeldeseite zuständig. Stattdessen wird die Authentifizierung durch eine Umleitung auf eine von @AWS angebotene Anmeldeseite durchgeführt. Nach erfolgreicher Authentifizierung wird der Benutzer zurück auf die Weboberfläche geleitet, wobei ein Session-Token übergeben wird, welches für die Dauer der Sitzung gültig ist. Dieses Token wird von der Weboberfläche bei jedem Request an die Backend-Services übermittelt, um die Identität des Benutzers zu verifizieren und den Zugriff auf die jeweiligen Ressourcen zu autorisieren. Gleiches gilt für den Logout, bei welchem der Benutzer kurzzeitig ebenfalls umgeleitet wird, um die Sitzung zu beenden.

== DevOps und Infrastructure as Code <sec:devops-iac>
Zu einer modernen Softwarearchitektur gehören neben dem reinen Applikations- und Infrastrukturdesign zwingend auch DevOps-Praktiken, die ein kontinuierliches Testen, Bauen und Ausrollen durch @CI und @CD ermöglichen. Die Architektur dieser Pipeline ist modular aufgebaut, wodurch sich neue Services aufwandsarm integrieren lassen. Der genaue Entwicklungszyklus wird in @sec:cicd-integration detailliert beschrieben.

Um das Deployment in die Cloud von @AWS vollautomatisiert durchzuführen, wurde @IaC angewandt. Die Infrastruktur wird dabei in imperativen Code geschrieben, welcher innerhalb der Pipeline ausgeführt wird, um die entsprechenden Cloud-Ressourcen zu provisionieren oder zu aktualisieren. Zum Einsatz kam hierbei @CDK in der Programmiersprache TypeScript.

Auf Code-Ebene nutzen die Komponenten für @IaC eine eigens entwickelte InfraLibrary. Diese abstrahiert und standardisiert komplexe Infrastruktur-Setups, wie das Deployment eines Service auf @ECS inklusive Lambda-Proxy, Routen des API Gateways und Integration von @AVP, in wenigen, wiederverwendbaren Zeilen Code. Durch diese Abstraktion wird sichergestellt, dass alle Services auf identischen infrastrukturellen Mustern basieren. Dies gewährleistet eine hohe Konsistenz, erleichtert das Debugging enorm und ermöglicht es, infrastrukturelle Anpassungen zentral vorzunehmen und global auf alle Services auszurollen.

Ergänzend zur InfraLibrary existiert das Projekt InfraBaseline. Dieses provisioniert die grundlegende Netzwerkinfrastruktur, den Cognito-Userpool auf @AWS, die Cloud-Map-Namespaces sowie die CloudFront-Distribution.

Der massive strategische Vorteil von @IaC zeigte sich im Projektverlauf mehrfach. So konnten Features isoliert getestet und die Infrastruktur jederzeit deterministisch auf ältere Stände zurückgerollt werden, wobei Applikationscode und Infrastruktur stets konsistent blieben. Besonders erfolgskritisch war der Ansatz mit @IaC, als der ursprüngliche Account bei @AWS aufgrund eines abgelaufenen Leases gesperrt wurde. Dank der vollständigen Implementierung als Code konnten sämtliche Ressourcen nahezu ohne manuelle Eingriffe in einem neuen Account hochgefahren werden. Ohne @IaC hätte dieser Vorfall eine stundenlange, extrem fehleranfällige manuelle Neuprovisionierung erfordert.

