= Kritik und Einordnung des Vibecoding <ch:vibecoding-critique>
Unter dem Begriff des „Vibe Coding“ beschreibt Andrej Karpathy im Februar 2025 eine neue Entwicklungsphilosophie, bei der das manuelle Schreiben von Code nahezu vollständig durch die Interaktion mit agentischen, auf großen Sprachmodellen basierenden Werkzeugen wie Antigravity oder Claude Code ersetzt wird @ibm_vibecoding_2026.

== Was lief gut
Ein Mono-Repo ermöglichte der KI zumindest grundsätzlich ein umfassenderes Kontextwissen über das Gesamtsystem, wenngleich fraglich bleibt, ob dieses Potenzial in der Praxis auch immer ausgeschöpft wurde. Außerdem führte dieser Ansatz durch den höheren Tokenverbrauch zu spürbar höheren Kosten (36 Euro für 2 Prompts). Positiv fiel vor allem die enorme Entwicklungsgeschwindigkeit auf. Insbesondere die Umsetzung des Frontends verlief gut. Dieser Geschwindigkeitsvorteil erwies sich, wie im folgenden Abschnitt beschrieben, zugleich als frustrierend. Nahezu alle im Projekt aufgetretenen Fehler konnten zudem mehr oder weniger zuverlässig von der KI behoben werden, und selbst ohne jegliche Vorerfahrung mit dem eingesetzten Tech-Stack (@AWS, Spring Boot) war es möglich, eigenständig Features zu entwickeln und auszuliefern. Für klassische, in sich abgeschlossene Fragestellungen erwies sich der Einsatz generativer KI als sehr hilfreich.

== Was lief eher schlecht
Den beschriebenen Vorteilen stand eine Reihe gravierender Probleme gegenüber. Es fehlt hier häufig jede Kontrolle darüber, was am Ende tatsächlich entsteht und wie dieses Ergebnis zustande kommt, während gleichzeitig eine unfassbar hohe Abhängigkeit (_Vendor Lock-in_) von den Anbietern entsteht. In der Gesamteinordnung eignet sich dieser Ansatz daher vor allem für einen Proof of Concept, sobald jedoch komplexere Software umgesetzt werden muss, stößt er an seine Grenzen. Jede Zeile Code, die der Agent (oder ein Mensch) schreibt, muss gewartet werden. Besonders bei komplexer Software ist die Unmenge an Code, die ein KI-Werkzeug erzeugt, nicht ideal. Besonders frustrierend war, dass letztlich niemand im Team mehr genau nachvollziehen konnte, wie die Anwendung im Detail funktioniert. Man promptet einen Fehler in die KI, wartet und hofft lediglich, dass die vorgeschlagene Lösung passt, ohne selbst beurteilen zu können, ob ein Fix tatsächlich greift. Das eigene Denken schaltet bei diesem Vorgehen zunehmend ab, man wartet nur noch passiv darauf, dass die KI etwas "macht". Ein Entwicklungsprozess, der sich als absolut langweilig erwies. Kleine, im Detail kaum nachvollziehbare Fehler führten dabei wiederholt dazu, dass die Software insgesamt nicht mehr funktionierte, ohne dass sich als Anwender noch klären ließ, woran es tatsächlich scheiterte.

Der Agent erledigte Aufgaben zudem häufig nur zur Hälfte: Mal vergaß er, zugehörige Tests anzupassen, mal ließ sich das Projekt anschließend gar nicht mehr kompilieren, weil schlicht Imports fehlten. Selbst bei expliziten Prompts wie "Behebe Compiler-Fehler und Tests" nahm er zwar Änderungen vor, ohne dass diese jedoch tatsächlich funktionierten, stattdessen traten neue oder andere Fehler auf. Viele Aspekte, die nicht bis ins Detail spezifiziert waren oder dem Agenten schlicht nicht im Kontext vorlagen, obwohl sie bereits durch andere Microservices vorgegeben waren, wurden dadurch falsch implementiert oder fälschlich angenommen. Auch der automatisierte GitHub-Reviewer erwies sich als problematisch: Einmal wurden dessen Vorschläge übernommen, woraufhin die Anwendung anschließend gar nicht mehr funktionierte.

Auch wirtschaftlich zeigten sich deutliche Schattenseiten. Ohne das kostenfreie Abonnement von Google hätte das Budget nicht gereicht. Ein einzelner Agenten-Durchlauf für einen Microservice verbrauchte bereits mehr als die Hälfte des ursprünglich veranschlagten Budgets von rund 50 €. Während des Projekts wurde mehr als 500-mal deployt; rechnet man nun das Budget hoch, kommt man auf astronomische Kosten. Gelernt hat das Team bei diesem Vorgehen letztlich kaum etwas. Verschärft wurde diese Situation durch eine hochgradig unübersichtliche Werkzeuglandschaft. Es existiert eine kaum überschaubare Zahl an Agentensystemen, die im Grunde denselben Zweck verfolgen. Claude Code, Codex, Antigravity, GitHub Copilot, Cursor oder OpenCode, jeweils sowohl als CLI- als auch als Desktop-Variante, jedes mit eigener Bedienung und Konfiguration, während zugleich in kurzen Abständen neue Tools und Versionen erscheinen und die aktive Nutzung häufig kostenpflichtige Abonnements voraussetzt. Mit einer Testabdeckung von über 80 % erreichte das Projekt zwar einen auf den ersten Blick guten Wert, doch lässt sich daraus kaum etwas über die tatsächliche Qualität der Implementierung oder der Tests selbst ableiten. Wie verlässlich die Anwendung letztlich wirklich getestet ist, bleibt offen.

== Herausforderungen
Die wirtschaftliche Nutzung des Vibe Codings wird oft mit einer drastischen Beschleunigung der Entwicklungszyklen begründet. Der finanzielle Aufwand für den Einsatz von Werkzeugen wie Claude Code hat sich von den ursprünglichen Lizenzgebühren einfacher Abonnements (20 US-Dollar pro Monat) hin zu erheblichen Token-Kosten entwickelt. Kosten für Teams, die Werkzeuge der KI nutzen, liegen heute eher zwischen 200 und teils mehr als 2.000 US-Dollar pro Entwickler und Monat @kanitkar_developer_2026. In Einzelfällen gibt es bereits Berichte von Mitarbeitern, die über 1,4 Millionen US-Dollar pro Monat verbrauchten @munis_meta_2026. Diese Investitionen führen durchaus zu einer höheren Anzahl an geschriebenen Zeilen Quellcode, doch sagt diese Metrik nichts über den tatsächlichen Nutzen aus. "Anybody who thinks that's a valid metric is too stupid to work at a tech company." - Linus Torvalds (über Zeilen von Code als KPI) @torvalds_linustechtips_2026.

Eine der umfangreichsten empirischen Untersuchungen zu diesem Phänomen ist die Langzeitstudie des Analyseunternehmens GitClear, die über einen Zeitraum von fünf Jahren die strukturellen Veränderungen von 211 Millionen Zeilen Quellcode aus Repositories führender Technologiekonzerne wie Google, Microsoft und Meta sowie globaler Großkonzerne auswertete. Die Ergebnisse zeigen eine Beschleunigung in qualitativer Degradierung moderner Codebasen @gitclear_ai_2025 @harding_gitclear_2025.

Der wohl folgenschwerste negative Effekt des Vibe Codings betrifft nicht die technische Beschaffenheit des Codes selbst, sondern die intellektuelle Kapazität des Entwicklerteams. Während technische Schulden ein im Code verankertes Phänomen beschreiben, das durch Refactoring behoben werden kann, entsteht durch den massiven Einsatz generativer Werkzeuge eine kognitive Verschuldung (Cognitive Debt). Diese beschreibt den fortschreitenden Verlust des Systemverständnisses, der sogenannten „Theorie des Systems“ @storey_cognitive_2026. Eine viermonatige Studie des MIT Media Lab, die im August 2025 veröffentlicht wurde, konnte unter Einsatz von EEG verschiedenste negative Effekte des Einsatzes generativer KI nachweisen @kosmyna_brain_2025. So zeigten Nutzer, die intensiv auf Unterstützung durch @LLM zurückgriffen, die schwächste neuronale Konnektivität und die geringste Gehirnaktivität. Als die Unterstützung durch KI entzogen wurde und die Probanden Aufgaben wieder eigenständig lösen mussten, zeigten sie eine signifikant reduzierte Alpha- und Beta-Konnektivität. Dieser Zustand der neuronalen Unteraktivierung (Neural Under-Engagement) belegt, dass das Gehirn nach längerer Nutzung von KI massive Schwierigkeiten hat, sich wieder eigenständig und tiefgehend auf komplexe kognitive Prozesse einzustellen.

== Zukunfts-Ausrichtung

Die praktische Evaluation im Rahmen dieses Projekts bestätigt das zentrale Versprechen des „Vibe Codings“: Für die rasche Umsetzung eines @MVP oder eines PoC ermöglicht der Einsatz agentischer Systeme der KI eine beachtliche Entwicklungsgeschwindigkeit, selbst ohne tiefgehende Vorkenntnisse im jeweiligen Tech-Stack. Allerdings entpuppt sich dieser initiale Geschwindigkeitsvorteil bei genauerer Betrachtung als zweischneidiges Schwert. Wie unsere praktischen Erfahrungen und die empirischen Befunde der GitClear-Studie untermauern, erkauft man sich die kurzfristige Produktivität häufig mit systematischen Qualitätsverlusten, inkonsistenten Implementierungen, unzureichend verifizierbaren Testabdeckungen und halluziniertem Code.

Weit schwerwiegender als diese rein technischen Defizite ist jedoch die schleichende Erosion der menschlichen Kompetenz. Die von uns empfundene Frustration bei der Fehlersuche und das passive „Abschalten des Gehirns“ während des Wartens auf den Agenten korrelieren präzise mit den neurobiologischen Erkenntnissen der Studie des MIT zur kognitiven Verschuldung (_Cognitive Debt_). Wenn Entwickler durch den kontinuierlichen Einsatz autonomer Agenten die „Theorie des Systems“ verlieren, entsteht bereits nach kurzen Projektphasen ein fataler Teufelskreis: Da nach der Erstellung des @MVP niemand von uns mehr ein ganzheitliches Code-Verständnis aufweist, muss die Behebung von Fehlern oder Architekturproblemen zwangsläufig wieder an den Agenten der KI delegiert werden. Dies treibt nicht nur die von uns beobachteten Token-Kosten in astronomische Höhen, sondern manifestiert eine langfristige technologische und wirtschaftliche Abhängigkeit (_Vendor Lock-in_) von großen Anbietern von @LLM. Sollte in Zukunft eine manuelle Überarbeitung des Codes erforderlich werden, beispielsweise durch weiter steigende Abonnements- und Tokenpreise oder komplexe Systemerweiterungen, ist eine menschliche Aufarbeitung der historisch gewachsenen Codebase kaum noch realisierbar und käme einer ressourcenintensiven Neuentwicklung gleich.

Für eine zukunftssichere und verantwortungsvolle Softwareentwicklung leitet sich daraus eine klare Differenzierung ab: Systeme der KI besitzen als unterstützende Werkzeuge eine enorme Daseinsberechtigung. Ihr Einsatz sollte jedoch bewusst und gezielt erfolgen, beispielsweise als interaktiver „Pair Programmer“ zur Beantwortung spezifischer Architekturfragen, zur Analyse von isolierten Fehlern oder zur Beschleunigung repetitiver Muster, bei denen das kritische Denken und die Entscheidungshoheit beim Menschen verbleiben. Das vollständige Überlassen des Entwicklungsprozesses an autonome Coding-Agenten erweist sich hingegen als nicht nachhaltig. Da Software im produktiven Unternehmensumfeld in der Regel über Jahrzehnte betrieben, gewartet und an neue Anforderungen angepasst werden muss, bleiben menschliche Experten, die das System in seiner tiefen Architektur durchdringen und beherrschen, auch in Zukunft unersetzlich.

