#set heading(numbering: "1.1")
#import "@preview/glossarium:0.5.10": gls, glspl

= Umsetzung und Workflow <ch:implementation-workflow>
Ein wesentlicher Bestandteil der praktischen Umsetzung umfasste den Einsatz von KI-gestützten Coding-Agenten wie Claude Code oder Google Antigravity. Vor Beginn der eigentlichen Projektphase wurden strategische Entscheidungen bezüglich deren Evaluierung getroffen, um eine bestmögliche Integration in den Entwicklungsprozess zu gewährleisten. Neben diesen modernen, #gls("LLM")-basierten Ansätzen fanden klassische Verfahren des Software-Lebenszyklus Anwendung. Hierzu zählen die Einrichtung einer Continuous-Integration- und Continuous-Deployment-Pipeline (CI/CD) sowie das automatisierte und manuelle Testen.

== Baseline <sec:baseline>
Zu Beginn der Implementierungsphase wurde die Entscheidung für ein Mono-Repository (Monorepo) getroffen. Die primäre Absicht bestand darin, den KI-Agenten den vollständigen Kontext über alle Microservices hinweg agnostisch bereitzustellen, ohne dass ein isolierter Wechsel zwischen verschiedenen Projektarchiven erforderlich ist. Obwohl es sich bei dem Vorhaben um eine vollständige Greenfield-Entwicklung handelte, wurde die initiale Baseline bewusst nicht agentisch, sondern lediglich KI-unterstützt und manuell entwickelt.

Im Rahmen dieser Baseline wurden alle grundlegenden Infrastrukturkomponenten mittels des AWS CDK implementiert. Dadurch konnte sichergestellt werden, dass die Services keine kostenintensiven Default-Ressourcen verwenden. Gleichzeitig förderte dieses Vorgehen das Systemverständnis innerhalb des Entwicklungsteams, was das spätere Debugging erheblich erleichterte. Da die Inter-Service-Kommunikation vollständig transparent war, ließ sich die Ursachenanalyse (Root-Cause-Analysis) im Fehlerfall schnell auf einzelne, isolierte Microservices eingrenzen. Dies erwies sich in einem verteilten System als fundamentaler Vorteil: Da autonome Agenten in komplexen AWS-Cloud-Infrastrukturen ohne vordefinierten Rahmen den Gesamtüberblick verlieren können, war es hocheffizient, den betroffenen Service vorab manuell zu identifizieren und den Agenten anschließend mit dedizierten Fehlermeldungen in einer isolierten Umgebung arbeiten zu lassen.

Ergänzend zur infrastrukturellen Basis wurde eine applikative Grundlage in Form eines *Template Service* geschaffen. Dieser diente den Coding-Agenten als struktureller Anker und Referenzarchitektur, um nahezu direkt lauffähige, neue Services zu generieren. Zu diesem Zweck wurde dieser Prototyp manuell implementiert, mit minimalen funktionalen Features ausgestattet und so auf die Infrastruktur abgestimmt, dass das Zusammenspiel aus Netzwerk, Autoscaling, DynamoDB-Datenbanken und dem API Gateway fehlerfrei funktionierte. Erst nach erfolgreicher Validierung dieser Basis wurden die Agenten eingesetzt, um die eigentliche Geschäftslogik in Kopien dieses Template-Service zu implementieren.

Die Praxis zeigte, dass die Coding-Agenten die vorgegebene Baseline sowohl auf infrastruktureller als auch auf applikativer Ebene weitgehend adaptierten, was zu einer konsistenten Systemlandschaft führte. Dennoch war auffällig, dass die Agenten vereinzelt unvorhergesehene und nicht an die Architekturrichtlinien angepasste Entscheidungen trafen. Beispielsweise versuchte ein Agent eigenständig, eine PostgreSQL-Datenbank zu provisionieren, was für den vorliegenden Anwendungsfall fachlich nicht erforderlich war und zudem durch den Verzicht auf vollständige Serverless-Eigenschaften die Betriebskosten unnötig erhöht hätte.

Auch der Einsatz des Monorepos wirkte sich im Hinblick auf das Kontextfenster (Context Window) der verwendeten Sprachmodelle positiv aus, da die Modelle jederzeit serviceübergreifendes Systemwissen in ihre Generierung einbeziehen konnten. Aus ökonomischer Sicht offenbarte dieser Ansatz jedoch auch Nachteile: Bei der Initiierung neuer Prompts fiel das Kontextfeld und insbesondere die Anzahl der Input-Tokens sehr groß aus, was zu erhöhten API-Gebühren führte. Zudem besteht bei sehr großen Kontexten das inhärente Risiko von Qualitätseinbußen, da @LLM dazu neigen, feine Details inmitten umfangreicher Datenmengen zu übersehen (Lost-in-the-Middle-Phänomen).

== Agentic Coding <sec:agentic-coding>
Unter Agentic Coding versteht man den Einsatz autonomer Software-Agenten auf Basis von @LLM:pl, die über klassische Code-Vervollständigung hinausgehen. Im Gegensatz zu Assistenzsystemen versucht man mit Coding-Agenten einen kontinuierlichen Zyklus (Agentic Loop) aus Analyse, Planung, Umsetzung sowie anschließender Verifikation abzubilden. Hierfür werden orchestrierende Agentensysteme häufig in Form von CLI-Anwendungen oder IDE-Integrationen verwendet, die den Agenten eine strukturierte Ausführungsumgebung bieten. Dies soll die selbstständige Bearbeitung komplexer Entwicklungsaufgaben ermöglichen. Im Rahmen dieser Arbeit wurden verschiedene solcher agentischen Werkzeuge evaluiert, um deren Eignung für den Aufbau einer ereignisgesteuerten Microservice-Architektur festzustellen.

=== Agents.MD / Claude.MD <sec:agents-md>
// (Luca, Gideon)

Ein wichtiger Aspekt guter Softwareentwicklung besteht darin, dass Architekturentscheidungen und Konventionen allen an der Software arbeitenden Entwicklern bekannt sein müssen, um diese anwenden zu können. Dieses Selbstverständnis führt zwangsweise dazu, dass auch autonom agierende Agenten die existierenden Regeln beachten müssen. Nur so kann Konsistenz gewährleistet werden. Um Coding-Agenten ebensolche projektbezogene Instruktionen und Kontext bereitzustellen, hat sich zunehmend die plattformübergreifende `AGENTS.md` als offener Standard @agents_md_website etabliert, der von Editoren wie Cursor und Agentensystemen wie Codex gelesen und respektiert wird. Im wesentlichen handelt es sich hierbei um eine Markdown-Datei, die ähnliche Funktionen wie die klassische `README.md` erfüllt, jedoch speziell für die Bereitstellung von Richtlinien, Konventionen und Projektinformationen für KI-Agenten konzipiert ist. Üblicherweise wird diese Datei im Wurzelverzeichnis eines Projekts abgelegt, um den Agenten einen zentralen Einstiegspunkt zu bieten. Oftmals ist es jedoch auch möglich, mehrere `AGENTS.md`-Dateien zu verwenden und diese in Unterverzeichnissen zu platzieren, um den Agenten kontextspezifische Informationen zu liefern. Hierzu sei angemerkt, dass durch die `AGENTS.md` zwar ein verbreiteter Standard existiert, es jedoch keine Garantie gibt, dass dieser stets eingehalten wird. So gibt es bis heute KI-Werkzeuge, die den Standard nicht respektieren. Dies führt zum Beispiel dazu, dass der Hersteller Anthropic mit Claude Code weiterhin ausschließlich sein proprietäres Dateiformat `CLAUDE.md` beachtet @claude_code_agents_issue_2025. Die Idee ist ansonsten identisch. // ¯\_(ツ)_/¯
Da im Rahmen dieser Arbeit mit verschiedenen Agentensystemen gearbeitet werden sollte, war es aus diesem Grund erforderlich, ebendiesen Umstand zu beachten und zu adressieren. So wurde neben der `AGENTS.md` auch eine `CLAUDE.md` erstellt, wobei letztere mithilfe eines \@Agents.md-Ausdrucks auf die `AGENTS.md` verweist.

Während des Projektverlaufs konnte immer wieder festgestellt werden, dass Agenten die `AGENTS.md`-Dateien erfolgreich gelesen hatten und deren Anweisungen bestmöglich befolgten. Zeitgleich wurde in Bezug auf die Dateien allerdings auch schnell ein Problem deutlich, Vorgaben können veralten oder im Konflikt stehen. Bei Änderungen an Architekturmustern ist es wiederholt dazu gekommen, dass `AGENTS.md`-Dateien nicht angepasst wurden, was zu späteren Zeitpunkten zu Problem geführt hat. Hierauf muss geachtet werden.

=== Antigravity <sec:antigravity>
Google's Antigravity #footnote[https://antigravity.google/] wird in drei grundlegend unterschiedlichen Versionen angeboten. Antigravity IDE #footnote[https://antigravity.google/product/antigravity-ide], welche die gewohnte VSCode #footnote[https://code.visualstudio.com/] Entwicklungsumgeben mit zahlreichen KI-Werkzeugen ergänzt.

Antigravity 2.0 #footnote[https://antigravity.google/product/antigravity-2] welche eine Agentenorchestrierungsplattform darstellt und den Texteditor entfernt und die Möglichkeit liefert auf verschiedene Art und Weise mit KI Agenten zu interagieren. Mit Antigravity 2.0 lassen sich außerdem Routineaufgaben planen und automatisiert erledigen. So kann zum Beispiel stündlich verlangt werden, mögliche Pull Requests zu mergen. Sogenannte Skills liefern den Agenten verschiedene Beschreibungen wie bestimmte Aufgaben zu erledigen sind.

Als letztes wird Antigravity, ähnlich zu Claude Code, auch als eine Kommandozeilenanwendung bereitgestellt #footnote[https://antigravity.google/product/antigravity-cli]. Diese bietet dem Nutzer ein ähnliches Erlebnis wie in Antigravity 2.0, beschränkt sich aber auf die Nutzung per Kommandozeile. Diese KI-Werkzeuge bieten den Sprachmodellen nicht nur Zugriff auf verschiedenste Kommandozeilenanwendungen und somit Zugriff auf bestimmte Bereiche der Hostmaschine, sondern ermöglichen es den Modellen weiter Subagenten zu erzeugen. Diese Subagenten werden für die Aufgabe als notwendig benannte Aufgaben zu erledigen.

Für dieses Projekt haben wir Antigravity 2.0 genutzt, um den von Konzernen gewünschten State-of-the-Art zu erleben und erlernen. Für jeden Microservice konnte ein neuer Kontext erstellt werden. Bevor der Agent zu implementieren beginnt, wird ein Planungsmodus verwendet, um den notwendigen Kontext einzulesen und sicherzustellen dass das Implementieren Schritt für Schritt erfolgt. Hierzu stellt der Agent teilweise beeindruckende Grafiken zur Architektur bereit. Der Plan lässt sich außerdem iterativ überarbeiten. Wenn der Plan bestätigt wird, implementiert die KI alle notwendigen Teile, so zumindest die Idee.

=== Claude Code <sec:claude-code>
// (Gideon)

=== OpenCode <sec:opencode>
// (Luca)

KI-Frameworks wie Claude Code, Antigravity oder Codex haben gemeinsam, dass sie üblicherweise für die Softwareentwicklung in Kombination mit den hauseigenen @LLM:pl und Abonnements der jeweiligen Hersteller wie Anthropic, Google oder OpenAI vorgesehen werden. Eine Anbindung der Systeme an @LLM:pl von Drittherstellern oder selbstbetriebenen Instanzen wird nicht unterstützt oder obliegt vorbehaltlich zukünftigen Einschränkungen. Es wird aktiv versucht, die Verwendung der Abonnements außerhalb der jeweiligen Plattformen zu unterbinden und die Ökosysteme durch die Bindung an die proprietären Dienste zu stärken. Insbesondere Anthropic hat sich zum Beispiel bestrebt gezeigt, eine Verwendung mit nicht unternehmenseigener Software zu verhindern und den Zugriff von zuwiderhandelnden Benutzern vollständig zu sperren @engelking_anthropic_2026. Eine Migration von einem Anbieter zu einem anderen wird hierdurch erheblich erschwert, obwohl die zur Anbindung von @LLM:pl verwendeten Schnittstellen üblicherweise einheitlich sind.

Bei dem Open-Source-Projekt OpenCode handelt es sich primär um eine CLI-Anwendung, welche eine Alternative zu den erwähnten proprietären Agentensystemen darstellen soll. Eine GUI-Variante ist ebenfalls verfügbar, derzeit jedoch noch in einer frühen Entwicklungsphase. Es bietet die Möglichkeit, beliebige @LLM:pl von verschiedensten Anbietern zu integrieren oder die Agenten auf selbstgehosteten Instanzen zu betreiben. OpenCode ist eine hochgradig konfigurierbar und erlaubt die Erweiterung durch Plugins. So ist es beispielsweise möglich, dass KI-Agenten, die auf verschiedenen Plattformen ausgeführt werden, miteinander kommunizieren und von einem einzigen kombinierten System orchestriert werden. Ein Austausch von verwendeten @LLM:pl oder Anbietern gestaltet sich durch die offene Architektur denkbar einfach und kann üblicherweise ohne Modifikationen der Agenten oder sonstigen Konfigurationen erfolgen.

Angesichts der beschriebenen vermeintlichen Vorteile von OpenCode, wurde sich dazu entschieden, auch dieses Werkzeug im Rahmen der Entwicklungsphase dieser Arbeit zu betrachten. So wurden zunächst sowohl diverse GPT- als auch Gemini-Modelle von OpenAI bzw. Google durch die Microsoft Azure API und anderen Abonnements an OpenCode angebunden, um diese für verschiedene Agenten zu verwenden. Es wurde zum Beispiel ein Architect-Agent definiert, welcher das Modell GPT-5.4 verwendet und für die Planung und Orchestrierung von Featureimplementierungen zuständig ist. Die Agenten, die an der tatsächlichen Implementierung arbeiten, wurden hingegen auf Basis von GPT-5.3-Codex ausgeführt, die ihr Verständnis vom Projekt wiederum von Explorer-Agenten mit Gemini-2.5-Flash beziehen. Auf diese Weise konnte einzelnen Agenten ein spezifisches Rollenverständnis zugewiesen werden, wodurch versucht wurde, die Stärken der jeweiligen Modelle gezielt zu nutzen. Die genaue verwendete Konfiguration kann im Ordner `.opencode` im Projektverzeichnis eingesehen werden.

Insbesondere der Web-UI-Service wurde maßgeblich mithilfe der eben beschriebenen Konstellation von Agenten und Modellen erfolgreich implementiert. Ein signifikanter Unterschied zwischen OpenCode und den proprietären Agentensystemen konnte dabei nicht festgestellt. Es gilt jedoch festzuhalten, dass zur effektiven Verwendung von OpenCode ein gewisses Maß an Einarbeitung empfehlenswert ist. Insbesondere die Konfiguration von Agenten mit Rollen trug stark zur Qualität der Ergebnisse bei, wobei entstehende API-Kosten durch die Auswahl von zur Komplexität passenden #gls("LLM")-Modellen erheblich reduziert werden konnten. Eine derartige manuelle Konfiguration erschien bei den proprietären Agentensystemen weniger erforderlich, führt jedoch auch dazu, dass die Systeme weniger an den individuellen Anwendungsfall angepasst wurden.

=== GitHub Copilot Reviewer <sec:github-reviewer>
// (Matthias)
Commit und Pull Requests von agentischer Entwicklung umfassen häufig große Mengen an Code - vorallem in Greenfield-Situationen wie in diesem Projekt. Um den Überblick über diese Änderungen behalten zu können, liefert GitHub mit GitHub Copilot Reviewer eine in die Platform integrierte KI-Unterstützung #footnote[https://docs.github.com/en/copilot/how-tos/use-copilot-agents/request-a-code-review/use-code-review]. Dieses Produkt soll dabei helfen die Quellcodeänderungen zu verstehen, Fehler zu finden oder auch selbstdefinierte Anweisungen durchzuführen. Der KI Review kann in den CI/CD Arbeitsfluss eingebunden werden, was einen hohen Grad an Automatisierung erlaubt.

Unsere Erfahrungen mit Copilot Review belaufen sich auf wenige Tests. In einem Drittel ($1/3$) Fällen wurde eine falsche Problemlösung vorgeschlagen.

== CI / CD Integration <sec:cicd-integration>
Als etabliertes Verfahren der modernen Softwareentwicklung wurde eine Continuous-Integration- und Continuous-Deployment-Pipeline eingerichtet. Diese erlaubt ein automatisiertes Deployment der aktuellen Softwareversion auf Knopfdruck. Hierdurch werden fehleranfällige manuelle Bereitstellungsprozesse eliminiert. Gleichzeitig stellt der Ansatz der kontinuierlichen Integration sicher, dass Modifikationen frühzeitig zusammengeführt werden, wodurch potenzielle Integrationskonflikte oder Laufzeitfehler in einem frühen Stadium sichtbar werden. Neben der Option, spezifische Feature-Branches manuell zu deployen, wird bei jedem Merge auf den geschützten Hauptzweig (`main` branch) automatisch das Deployment aller vom Commit betroffenen Microservices initiiert.

Die Pipeline ist technologisch auf Basis von GitHub Actions realisiert. Der Workflow umfasst das automatisierte Kompilieren des Java-Backend-Codes sowie die Ausführung der Unit-Tests für die Applikation und den TypeScript-basierten IaC-Code. Nach erfolgreicher Verifikation wird das Docker-Image erstellt und in die Amazon Elastic Container Registry (ECR) gepusht. Im anschließenden Schritt initiiert die Pipeline mittels des Befehls `cdk deploy` das infrastrukturelle Deployment, wodurch sowohl die modifizierten Cloud-Ressourcen aktualisiert als auch die neuen Applikations-Images auf den ECS-Fargate-Instanzen ausgerollt werden.

== Testen (Manuell) <sec:manual-testing>
// (Gideon)

== Optimierung <sec:optimization>
// (Luca)

Während der Entwicklungsphase wurde mithilfe von ausführlichen KI-Prompts und entsprechend angepassten `AGENTS.md`-Dateien versucht, die Testabdeckung des Gesamtsystems sicherzustellen. Gleichzeitig wurde hierbei angestrebt, allgemeine Codestrukturen und Konventionen festzulegen. Schnell hat sich dies jedoch insbesondere durch die Verwendung von unterschiedlichen @LLM:pl als kein triviales Unterfangen herausgestellt, da die Modelle jeweils mit ihren spezifischen Präferenzen und Verhaltensmustern daherkamen. So wurden beispielsweise Regeln unterschiedlich stark eingehalten, wodurch es schließlich dazu gekommen ist, dass die Testabdeckung für einige Services entweder stark oder vollkommen vernachlässigt wurde. Insbesondere der Web-UI-Service verblieb eine lange Zeit ohne Tests. Dies verbesserte sich erst nachdem eine Codeabdeckung explizit gefordert wurde. Es ist davon auszugehen, dass besser ausformulierte `AGENTS.md`-Dateien diese Situation hätten verbessern können. Zeitgleich hätte dies bedeutet, dass bestenfalls bereits zu Anfang des Projekts fertige Architekturpläne, Ordnersturkturen und Konventionen hätten bereitstehen müssen. Dies war uns nicht möglich und erschien wenig praktikabel.

Nach Fertigstellung der Implementierung des @MVP wurde die Testabdeckung der einzelnen Microservices des PeerReview-Systems ermittelt, um den jeweiligen #gls("CRAP")-Index zu berechnen. Für diesen wurde festgelegt, dass ein maximaler Wert von 30 zu akzeptieren ist. Beim Vergleich der Indexwerte mit dem Schwellwert wurden diverse Codestellen identifiziert, die basierend auf den geltenden Bedingungen als kritisch einzustufen waren und einer Optimierung bedurften.

#figure(
  caption: [Top CRAP-Index-Ausreißer vor der Optimierung],
  table(
    columns: 4,
    [*Service*], [*Klasse / Komponente*], [*Methode*], [*CRAP-Score*],
    [Web-UI], [Submissions.tsx], [mapConfigToDisplay], [407.1],
    [Web-UI], [Dashboard.tsx], [fetchTasks], [314.5],
    [Web-UI], [SubmissionModal.tsx], [SubmissionModal], [197.5],
    [Communication-Service], [ChatService], [getChat], [132.0],
    [Response-Service], [BedrockProxyClient], [generateReview], [132.0],
  )
)

== Dokumentation <sec:documentation>
// (Claude, Matthias)
Für die API Endpunkte liefert die OpenAPI Spezifikationen umfangreiche Dokumentation. Aus diesen OpenAPI Spezifikationen wird durch ein Phython Skript eine Kollektion an Postman Ressourcen erstellt. FÜr die Agenten stehen spezifische Architekturentscheidungen, API-Endpunkte, Datenbankenschemata und Beispiel-Payloads bereit.
