#set heading(numbering: "1.1")
#import "@preview/glossarium:0.5.10": gls, glspl

= Umsetzung und Workflow <ch:implementation-workflow>
Ein wesentlicher Bestandteil der praktischen Umsetzung umfasste den Einsatz von Coding-Agenten auf Basis von KI wie Claude Code oder Google Antigravity. Vor Beginn der eigentlichen Projektphase wurden strategische Entscheidungen bezüglich deren Evaluierung getroffen, um eine bestmögliche Integration in den Entwicklungsprozess zu gewährleisten. Neben diesen modernen, #gls("LLM")-basierten Ansätzen fanden klassische Verfahren des Software-Lebenszyklus Anwendung. Hierzu zählen die Einrichtung einer Pipeline für @CI und @CD sowie das automatisierte und manuelle Testen.

== Baseline <sec:baseline>
Zu Beginn der Implementierungsphase wurde die Entscheidung für ein Mono-Repository (Monorepo) getroffen. Die primäre Absicht bestand darin, den KI-Agenten den vollständigen Kontext über alle Microservices hinweg agnostisch bereitzustellen, ohne dass ein isolierter Wechsel zwischen verschiedenen Projektarchiven erforderlich ist. Obwohl es sich bei dem Vorhaben um eine vollständige Greenfield-Entwicklung handelte, wurde die initiale Baseline bewusst nicht agentisch, sondern lediglich KI-unterstützt und manuell entwickelt.

Im Rahmen dieser Baseline wurden alle grundlegenden Infrastrukturkomponenten mittels @CDK implementiert. Dadurch konnte sichergestellt werden, dass die Services keine kostenintensiven Default-Ressourcen verwenden. Gleichzeitig förderte dieses Vorgehen unser Systemverständnis, was das spätere Debugging erheblich erleichterte. Da die Inter-Service-Kommunikation vollständig transparent war, ließ sich die Ursachenanalyse (Root-Cause-Analysis) im Fehlerfall in der Regel auf einzelne, isolierte Microservices eingrenzen. Dies erwies sich in einem verteilten System als fundamentaler Vorteil: Da autonome Agenten in komplexen Cloud-Infrastrukturen auf @AWS ohne vordefinierten Rahmen den Gesamtüberblick verlieren können, war es hocheffizient, den betroffenen Service vorab manuell zu identifizieren und den Agenten anschließend mit dedizierten Fehlermeldungen in einer isolierten Umgebung arbeiten zu lassen.

Ergänzend zur infrastrukturellen Basis wurde eine applikative Grundlage in Form eines Template Service geschaffen. Dieser diente den Coding-Agenten als struktureller Anker und Referenzarchitektur, um nahezu direkt lauffähige, neue Services zu generieren. Zu diesem Zweck wurde dieser Prototyp manuell implementiert, mit minimalen funktionalen Features ausgestattet und so auf die Infrastruktur abgestimmt, dass das Zusammenspiel aus Netzwerk, Autoscaling, DynamoDB-Datenbanken und dem API Gateway fehlerfrei funktionierte. Erst nach erfolgreicher Validierung dieser Basis wurden die Agenten eingesetzt, um die eigentliche Geschäftslogik in Kopien dieses Template-Service zu implementieren.

Die Praxis zeigte, dass die Coding-Agenten die vorgegebene Baseline sowohl auf infrastruktureller als auch auf applikativer Ebene weitgehend adaptierten, was zu einer konsistenten Systemlandschaft führte. Dennoch war auffällig, dass die Agenten vereinzelt unvorhergesehene und nicht an die Architekturrichtlinien angepasste Entscheidungen trafen. Beispielsweise versuchte ein Agent eigenständig, eine PostgreSQL-Datenbank zu provisionieren, was für den vorliegenden Anwendungsfall fachlich nicht erforderlich war und zudem durch den Verzicht auf vollständige Serverless-Eigenschaften die Betriebskosten unnötig erhöht hätte.

Auch der Einsatz des Monorepos wirkte sich im Hinblick auf das Kontextfenster (Context Window) der verwendeten Sprachmodelle positiv aus, da die Modelle jederzeit serviceübergreifendes Systemwissen in ihre Generierung einbeziehen konnten. Aus ökonomischer Sicht offenbarte dieser Ansatz jedoch auch Nachteile: Bei der Initiierung neuer Prompts fiel das Kontextfeld und insbesondere die Anzahl der Input-Tokens sehr groß aus, was zu erhöhten Gebühren für APIs führte. Zudem besteht bei sehr großen Kontexten das inhärente Risiko von Qualitätseinbußen, da @LLM dazu neigen, feine Details inmitten umfangreicher Datenmengen zu übersehen (Lost-in-the-Middle-Phänomen).

== Agentic Coding <sec:agentic-coding>
Unter Agentic Coding versteht man den Einsatz autonomer Software-Agenten auf Basis von @LLM:pl, die über klassische Code-Vervollständigung hinausgehen. Im Gegensatz zu Assistenzsystemen versucht man mit Coding-Agenten einen kontinuierlichen Zyklus (Agentic Loop) aus Analyse, Planung, Umsetzung sowie anschließender Verifikation abzubilden. Hierfür werden orchestrierende Agentensysteme häufig in Form von CLI-Anwendungen oder IDE-Integrationen verwendet, die den Agenten eine strukturierte Ausführungsumgebung bieten. Dies soll die selbstständige Bearbeitung komplexer Entwicklungsaufgaben ermöglichen. Im Rahmen dieser Arbeit wurden verschiedene solcher agentischen Werkzeuge evaluiert, um deren Eignung für den Aufbau einer ereignisgesteuerten Microservice-Architektur festzustellen.

=== Agents.MD / Claude.MD <sec:agents-md>
// (Luca, Gideon)

Ein wichtiger Aspekt guter Softwareentwicklung besteht darin, dass Architekturentscheidungen und Konventionen allen an der Software arbeitenden Entwicklern bekannt sein müssen, um diese anwenden zu können. Dieses Selbstverständnis führt zwangsweise dazu, dass auch autonom agierende Agenten die existierenden Regeln beachten müssen. Nur so kann Konsistenz gewährleistet werden. Um Coding-Agenten ebensolche projektbezogene Instruktionen und Kontext bereitzustellen, hat sich zunehmend die plattformübergreifende `AGENTS.md` als offener Standard @agents_md_website etabliert, der von Editoren wie Cursor und Agentensystemen wie Codex gelesen und respektiert wird. Im Wesentlichen handelt es sich hierbei um eine Markdown-Datei, die ähnliche Funktionen wie die klassische `README.md` erfüllt, jedoch speziell für die Bereitstellung von Richtlinien, Konventionen und Projektinformationen für KI-Agenten konzipiert ist. Üblicherweise wird diese Datei im Wurzelverzeichnis eines Projekts abgelegt, um den Agenten einen zentralen Einstiegspunkt zu bieten. Oftmals ist es jedoch auch möglich, mehrere `AGENTS.md`-Dateien zu verwenden und diese in Unterverzeichnissen zu platzieren, um den Agenten kontextspezifische Informationen zu liefern. Hierzu sei angemerkt, dass durch die `AGENTS.md` zwar ein verbreiteter Standard existiert, es jedoch keine Garantie gibt, dass dieser stets eingehalten wird. So gibt es bis heute KI-Werkzeuge, die den Standard nicht respektieren. Dies führt zum Beispiel dazu, dass der Hersteller Anthropic mit Claude Code weiterhin ausschließlich sein proprietäres Dateiformat `CLAUDE.md` beachtet @claude_code_agents_issue_2025. Die Idee ist ansonsten identisch. // ¯\_(ツ)_/¯
Da im Rahmen dieser Arbeit mit verschiedenen Agentensystemen gearbeitet werden sollte, war es aus diesem Grund erforderlich, ebendiesen Umstand zu beachten und zu adressieren. So wurde neben der `AGENTS.md` auch eine `CLAUDE.md` erstellt, wobei letztere mithilfe eines \@Agents.md-Ausdrucks auf die `AGENTS.md` verweist.

Während des Projektverlaufs konnte immer wieder festgestellt werden, dass Agenten die `AGENTS.md`-Dateien erfolgreich gelesen hatten und deren Anweisungen bestmöglich befolgten. Zeitgleich wurde in Bezug auf die Dateien allerdings auch schnell ein Problem deutlich: Vorgaben können veralten oder im Konflikt stehen. Bei Änderungen an Architekturmustern ist es wiederholt dazu gekommen, dass `AGENTS.md`-Dateien nicht angepasst wurden, was zu späteren Zeitpunkten zu Problemen geführt hat. Hierauf muss geachtet werden.

=== Antigravity <sec:antigravity>
Google's Antigravity @google_antigravity_2026 wird in drei grundlegend unterschiedlichen Versionen angeboten. Antigravity IDE @google_antigravityide_2026 ergänzt die gewohnte Entwicklungsumgebung VSCode @vscode_website_nodate mit zahlreichen Werkzeugen der KI.

Antigravity 2.0 @google_antigravity2_2026 ist eine Agentenorchestrierungsplattform, die den Texteditor entfernt und die Möglichkeit liefert, auf verschiedene Art und Weise mit Agenten der KI zu interagieren. Mit Antigravity 2.0 lassen sich außerdem Routineaufgaben planen und automatisiert erledigen. So kann zum Beispiel stündlich verlangt werden, mögliche Pull Requests zu mergen. Sogenannte Skills liefern den Agenten verschiedene Beschreibungen wie bestimmte Aufgaben zu erledigen sind.

Zuletzt wird Antigravity, ähnlich wie Claude Code, auch als eine Kommandozeilenanwendung bereitgestellt @google_antigravitycli_2026. Diese bietet dem Nutzer ein ähnliches Erlebnis wie in Antigravity 2.0, beschränkt sich aber auf die Nutzung per Kommandozeile. Diese KI-Werkzeuge bieten den Sprachmodellen nicht nur Zugriff auf verschiedenste Kommandozeilenanwendungen und somit Zugriff auf bestimmte Bereiche der Hostmaschine, sondern ermöglichen es den Modellen ebenso weitere Subagenten zu erzeugen. Diese Subagenten werden erzeugt, um die für die Aufgabe als notwendig erachteten Teilaufgaben zu erledigen.

Für dieses Projekt haben wir Antigravity 2.0 genutzt, um den von Konzernen gewünschten State-of-the-Art zu erleben und erlernen. Für jeden Microservice konnte ein neuer Kontext erstellt werden. Bevor der Agent zu implementieren beginnt, wird ein Planungsmodus verwendet, um den notwendigen Kontext einzulesen und sicherzustellen, dass die Implementierung Schritt für Schritt erfolgt. Hierzu stellt der Agent teilweise beeindruckende Grafiken zur Architektur bereit. Der Plan lässt sich außerdem iterativ überarbeiten. Wenn der Plan bestätigt wird, implementiert die KI alle notwendigen Teile, so zumindest die Idee.

=== Claude Code <sec:claude-code>

Claude Code #footnote[https://www.claude.com/product/claude-code] ist die Agentenplattform des Herstellers Anthropic und wurde im Rahmen dieses Projekts am intensivsten eingesetzt. Neben der Kommandozeilenanwendung steht das Werkzeug auch als Extension für gängige IDEs wie VS Code zur Verfügung, was die im Rahmen dieser Arbeit primär genutzte Variante war; der Agent liest und editiert Dateien eigenständig, führt Shell-Befehle (u. a. `mvn`, `npm`, `git`, `cdk`) aus und lässt sich, ähnlich wie bei Antigravity 2.0, über einen eigenen Planungsmodus (Plan Mode) zunächst einen Umsetzungsplan erarbeiten und bestätigen, bevor die eigentliche Implementierung beginnt. Wie auch die übrigen betrachteten Werkzeuge kann Claude Code bei Bedarf Subagenten für klar abgegrenzte Teilaufgaben erzeugen. Die projektspezifischen Konventionen wurden dem Werkzeug, wie in @sec:agents-md beschrieben, über die Datei `CLAUDE.md` bereitgestellt.

Im direkten Vergleich zu den übrigen im Projekt eingesetzten Werkzeugen lieferte Claude Code durch den Zugriff auf sehr leistungsfähige Modelle (u. a. Claude Opus 4.8) tendenziell die qualitativ überzeugendsten Ergebnisse, war dabei aber mit Abstand das teuerste Werkzeug. Die dadurch entstehenden hohen Token-Kosten führten in der Praxis dazu, dass bewusst sparsamer promptet und iteriert wurde als mit günstigeren Alternativen, was die eigentlich zu erwartende Entwicklungsgeschwindigkeit spürbar relativierte.

Am Beispiel der Implementierung von Notification Service und Response Service, die beide vollständig mit Claude Code entwickelt wurden, zeigte sich, dass das Werkzeug bei klar vorgegebenem architektonischem Kontext solide Ergebnisse liefert: Etablierte Muster aus anderen Services des Monorepos, etwa das Single-Table-Design von DynamoDB oder die Verwendung vorsignierter URLs für den Zugriff auf @S3, wurden korrekt übernommen und konsistent weitergeführt, ohne dass diese im Detail vorgegeben werden mussten. Auch eigenständig vorgeschlagene Entwurfsmuster, etwa ein Strategy Pattern zur Anbindung mehrerer Benachrichtigungskanäle (Discord, E-Mail, Slack), erwiesen sich als sinnvoll und leicht um weitere Kanäle erweiterbar.

Gleichzeitig zeigte sich wiederholt, dass sich die Ausgaben des Werkzeugs nicht ungeprüft übernehmen lassen. So erzeugte Claude Code beispielsweise eine Beschreibung des Notification-Controllers, die dessen tatsächliches Verhalten falsch wiedergab: Die Dokumentation behauptete, es werde stets ein einheitlicher Erfolgsstatus zurückgegeben, obwohl der Code bereits differenziert zwischen vollständigem, teilweisem und fehlgeschlagenem Versand einer Benachrichtigung unterschied. Dieser Widerspruch fiel erst bei einer nachträglichen Prüfung auf und musste korrigiert werden. Ähnlich gelagert waren Fehler, die lokal unentdeckt blieben, weil einzelne Komponenten wie ein Listener für @SQS lokal per Konfiguration deaktiviert sind, und erst beim tatsächlichen Deployment sichtbar geworden wären, etwa ein zunächst fehlender, explizit zu definierender `ObjectMapper`-Bean. Auch typische Fallstricke aus dem Zusammenspiel von Lombok und dem SDK von @AWS (z. B. methodenbasierte DynamoDB-Annotationen, die nicht auf Lombok-generierten Feldern stehen dürfen) traten zunächst unbemerkt auf und mussten identifiziert werden. Diese Erfahrungen bestätigen den in @sec:agents-md beschriebenen Befund: Eine `CLAUDE.md`-Datei ist kein einmalig geschriebenes, vollständiges Regelwerk, sondern wächst erst durch das Auffangen konkreter, selbst erlebter Fehler zu einem wirksamen Werkzeug heran. Ohne einen Entwickler, der die Ergebnisse aufmerksam prüft, gegen die tatsächliche Codebasis abgleicht und Vorgaben entsprechend nachschärft, wären mehrere dieser Probleme unbemerkt geblieben oder erst in Produktion aufgefallen.

=== OpenCode <sec:opencode>
// (Luca)

Frameworks der KI wie Claude Code, Antigravity oder Codex haben gemeinsam, dass sie üblicherweise für die Softwareentwicklung in Kombination mit den hauseigenen @LLM:pl und Abonnements der jeweiligen Hersteller wie Anthropic, Google oder OpenAI vorgesehen werden. Eine Anbindung der Systeme an @LLM:pl von Drittherstellern oder selbstbetriebenen Instanzen wird nicht unterstützt oder obliegt vorbehaltlich zukünftigen Einschränkungen. Es wird aktiv versucht, die Verwendung der Abonnements außerhalb der jeweiligen Plattformen zu unterbinden und die Ökosysteme durch die Bindung an die proprietären Dienste zu stärken. Insbesondere Anthropic hat sich zum Beispiel bestrebt gezeigt, eine Verwendung mit nicht unternehmenseigener Software zu verhindern und den Zugriff von zuwiderhandelnden Benutzern vollständig zu sperren @engelking_anthropic_2026. Eine Migration von einem Anbieter zu einem anderen wird hierdurch erheblich erschwert, obwohl die zur Anbindung von @LLM:pl verwendeten Schnittstellen üblicherweise einheitlich sind.

Bei dem Open-Source-Projekt OpenCode handelt es sich primär um eine CLI, welche eine Alternative zu den erwähnten proprietären Agentensystemen darstellen soll. Eine Variante mit GUI ist ebenfalls verfügbar, derzeit jedoch noch in einer frühen Entwicklungsphase. Es bietet die Möglichkeit, beliebige @LLM:pl von verschiedensten Anbietern zu integrieren oder die Agenten auf selbstgehosteten Instanzen zu betreiben. OpenCode ist hochgradig konfigurierbar und erlaubt die Erweiterung durch Plugins. So ist es beispielsweise möglich, dass Agenten der KI, die auf verschiedenen Plattformen ausgeführt werden, miteinander kommunizieren und von einem einzigen kombinierten System orchestriert werden. Ein Austausch von verwendeten @LLM:pl oder Anbietern gestaltet sich durch die offene Architektur denkbar einfach und kann üblicherweise ohne Modifikationen der Agenten oder sonstigen Konfigurationen erfolgen.

Angesichts der beschriebenen vermeintlichen Vorteile von OpenCode wurde sich dazu entschieden, auch dieses Werkzeug im Rahmen der Entwicklungsphase dieser Arbeit zu betrachten. So wurden zunächst sowohl diverse GPT- als auch Gemini-Modelle von OpenAI bzw. Google durch die Schnittstelle zur Anwendungsprogrammierung von Microsoft Azure und andere Abonnements an OpenCode angebunden, um diese für verschiedene Agenten zu verwenden. Es wurde zum Beispiel ein Architect-Agent definiert, welcher das Modell GPT-5.4 verwendet und für die Planung und Orchestrierung von Featureimplementierungen zuständig ist. Die Agenten, die an der tatsächlichen Implementierung arbeiten, wurden hingegen auf Basis von GPT-5.3-Codex ausgeführt, die ihr Verständnis vom Projekt wiederum von Explorer-Agenten mit Gemini-2.5-Flash beziehen. Auf diese Weise konnte einzelnen Agenten ein spezifisches Rollenverständnis zugewiesen werden, wodurch versucht wurde, die Stärken der jeweiligen Modelle gezielt zu nutzen. Die genaue verwendete Konfiguration kann im Ordner `.opencode` im Projektverzeichnis eingesehen werden.

Insbesondere der Service der Web-UI wurde maßgeblich mithilfe der eben beschriebenen Konstellation von Agenten und Modellen erfolgreich implementiert. Ein signifikanter Unterschied zwischen OpenCode und den proprietären Agentensystemen konnte dabei nicht festgestellt werden. Es gilt jedoch festzuhalten, dass zur effektiven Verwendung von OpenCode ein gewisses Maß an Einarbeitung empfehlenswert ist. Insbesondere die Konfiguration von Agenten mit Rollen trug stark zur Qualität der Ergebnisse bei, wobei entstehende Kosten für APIs durch die Auswahl von zur Komplexität passenden #gls("LLM")-Modellen erheblich reduziert werden konnten. Eine derartige manuelle Konfiguration erschien bei den proprietären Agentensystemen weniger erforderlich, führte jedoch auch dazu, dass die Systeme weniger an den individuellen Anwendungsfall angepasst wurden.

=== GitHub Copilot Reviewer <sec:github-reviewer>
// (Matthias)
Commit und Pull Requests von agentischer Entwicklung umfassen häufig große Mengen an Code - vor allem in Greenfield-Situationen wie in diesem Projekt. Um den Überblick über diese Änderungen behalten zu können, liefert GitHub mit GitHub Copilot Reviewer eine in die Plattform integrierte Unterstützung durch KI @github_copilot_review_2026. Dieses Produkt soll dabei helfen, die Quellcodeänderungen zu verstehen, Fehler zu finden oder auch selbstdefinierte Anweisungen durchzuführen. Die Review durch KI kann in den Arbeitsfluss für @CI und @CD eingebunden werden, was einen hohen Grad an Automatisierung erlaubt.

Unsere Erfahrungen mit Copilot Review belaufen sich auf wenige Tests. In einem Drittel ($1/3$) der Fälle wurde eine falsche Problemlösung vorgeschlagen.

== Integration von @CI und @CD <sec:cicd-integration>
Als etabliertes Verfahren der modernen Softwareentwicklung wurde eine Pipeline für @CI und @CD eingerichtet. Diese erlaubt ein automatisiertes Deployment der aktuellen Softwareversion auf Knopfdruck. Hierdurch werden fehleranfällige manuelle Bereitstellungsprozesse eliminiert. Gleichzeitig stellt der Ansatz der kontinuierlichen Integration sicher, dass Modifikationen frühzeitig zusammengeführt werden, wodurch potenzielle Integrationskonflikte oder Laufzeitfehler in einem frühen Stadium sichtbar werden. Neben der Option, spezifische Feature-Branches manuell zu deployen, wird bei jedem Merge auf den geschützten Hauptzweig (`main` branch) automatisch das Deployment aller vom Commit betroffenen Microservices initiiert.

Die Pipeline ist technologisch auf Basis von GitHub Actions realisiert. Der Workflow umfasst das automatisierte Kompilieren des Java-Backend-Codes sowie die Ausführung der Unit-Tests für die Applikation und den TypeScript-basierten Code für @IaC. Nach erfolgreicher Verifikation wird das Docker-Image erstellt und in @ECR gepusht. Im anschließenden Schritt initiiert die Pipeline mittels des Befehls `cdk deploy` das infrastrukturelle Deployment, wodurch sowohl die modifizierten Cloud-Ressourcen aktualisiert als auch die neuen Applikations-Images auf Instanzen mit @ECS Fargate ausgerollt werden.

Lokal lässt sich die Software nicht ausführen, weil eine hohe Abhängigkeit zu Cloud-Ressourcen besteht. Auch wenn einige Services, wie eine asynchrone Queue, lokal abgebildet werden könnten, ist die Integration von Cognito, dem API Gateway, DynamoDB oder Verified Permissions auf @AWS sehr komplex und aus diesem Grundnicht Teil des @MVP.

Die Web-UI bietet jedoch die Möglichkeit, lokal gestartet zu werden und weiterhin die Backend-Services zu nutzen. Dazu kommt ein Reverse Proxy zum Einsatz, der alle Anfragen der lokal instanziierten Web-UI an die Umgebung auf @AWS weiterleitet. Hierzu wird der Befehl `npm run dev` im Verzeichnis der Web-UI ausgeführt. Einige Features, wie beispielsweise Ereignisse über @SSE, sind hierbei zwar limitiert, was für eine Entwicklungsumgebung aber akzeptabel ist.

== Manuelles Testen <sec:manual-testing>
// (Gideon)
Neben der automatisierten Testabdeckung wurde das System während der gesamten Entwicklungszeit auch manuell überprüft. Im Vordergrund stand dabei ein klassischer Klicktest über die Web-UI, bei dem die zentralen Abläufe wie Einreichung, Zuweisung und Begutachtung wiederholt durchgespielt wurden. Ergänzend wurden einzelne REST-Endpunkte gezielt über Postman angesprochen, um Anfragen unabhängig von der Oberfläche zu prüfen. Da ein wesentlicher Teil der Kommunikation zwischen den Services über @SQS erfolgt, wurden zudem Nachrichten manuell in die jeweiligen Queues geschrieben und die daraus resultierende Verarbeitung sowie die abgelegten Ergebnisse kontrolliert.

Auffälligkeiten aus diesen Tests wurden nicht separat dokumentiert oder als Ticket erfasst, sondern direkt im Code behoben und über die bestehende @CI/@CD Pipeline (siehe @sec:cicd-integration) umgehend wieder ausgerollt. Dieses pragmatische Vorgehen war durch die geringe Teamgröße und die kurzen Deployment-Zyklen möglich und sorgte für eine schnelle Rückkopplung zwischen Testen und Implementierung.

== Automatisierte Testabdeckung <sec:automated-testing>
Neben der manuellen Qualitätssicherung wurde großer Wert auf eine fundierte automatisierte Testabdeckung gelegt. Da das System eine verteilte Microservice-Architektur aufweist, lag der Fokus auf der Isolation einzelner Domänen mittels Unit-Tests. Für die Backend-Services (Java/Spring Boot) wurde das Mockito-Framework eingesetzt, um externe Abhängigkeiten wie Datenbanken oder Dienste von @AWS (z. B. @S3 und @SQS) zuverlässig zu simulieren. Die Metriken zur Codeabdeckung wurden durch das JaCoCo-Plugin ermittelt und direkt als Qualitätsgate in den Build-Prozess (`mvn verify`) integriert.

Im Frontend (`web-ui`) erfolgte die automatisierte Prüfung mittels Vitest und der React Testing Library. Hierbei wurden sowohl funktionale Logik als auch komplexe Interaktionen der UI isoliert getestet. Auch im Frontend wurde die Metrikerfassung in den Workflow für @CI eingebunden.

Im Infrastrukturbereich wurde durch das Anwenden von @CDK die Möglichkeit geschaffen, auch den Infrastrukturcode automatisch durch Unit-Tests zu testen. Während der Entwicklung hat sich dabei gezeigt, dass sich dies insbesondere unter dem Einsatz von KI für die Entwicklung von Code als hilfreich erweist, da Tests mögliche ungewollte Infrastrukturänderungen aufdecken.

Wie im nachfolgenden Abschnitt näher erläutert wird (siehe @sec:optimization), spielt die so ermittelte Testabdeckung eine tragende Rolle bei der qualitativen Bewertung des Quellcodes und bildete die mathematische Grundlage zur Berechnung des Index @CRAP, durch welchen besonders fehleranfällige und unzureichend getestete Bereiche identifiziert werden konnten.

== Optimierung <sec:optimization>
// (Luca)

Während der Entwicklungsphase wurde mithilfe von ausführlichen Prompts für KI und entsprechend angepassten `AGENTS.md`-Dateien versucht, die Testabdeckung des Gesamtsystems sicherzustellen. Gleichzeitig wurde hierbei angestrebt, allgemeine Codestrukturen und Konventionen festzulegen. Schnell hat sich dies jedoch insbesondere durch die Verwendung von unterschiedlichen @LLM:pl als kein triviales Unterfangen herausgestellt, da die Modelle jeweils mit ihren spezifischen Präferenzen und Verhaltensmustern daherkamen. So wurden beispielsweise Regeln unterschiedlich stark eingehalten, wodurch es schließlich dazu gekommen ist, dass die Testabdeckung für einige Services entweder stark oder vollkommen vernachlässigt wurde. Insbesondere der Service der Web-UI verblieb bis zu deren Fertigstellung ohne Tests. Dies verbesserte sich erst, nachdem eine Codeabdeckung explizit gefordert wurde. Es ist davon auszugehen, dass besser ausformulierte `AGENTS.md`-Dateien diese Situation hätten verbessern können. Zeitgleich hätte dies bedeutet, dass bestenfalls bereits zu Anfang des Projekts fertige Architekturpläne, Ordnerstrukturen und Konventionen hätten bereitstehen müssen. Dies war uns nicht möglich und erschien wenig praktikabel.

Dieser eben beschriebene erste negative Eindruck bezüglich der Testabdeckung wurde nach Fertigstellung der Implementierung des @MVP weiter untersucht. Hierzu wurde zunächst die Codeabdeckung der einzelnen Microservices des PeerReview-Systems ermittelt, um anschließend den jeweiligen #gls("CRAP")-Index zu berechnen. Für diesen wurde festgelegt, dass ein maximaler Wert von 30 zu akzeptieren ist. Beim Vergleich der Indexwerte mit dem Schwellwert wurden daraufhin diverse Codestellen identifiziert, die basierend auf den geltenden Bedingungen als kritisch einzustufen waren und einer Optimierung bedurften (siehe @fig:crap_before).

#figure(
  caption: [Top-Ausreißer beim Index @CRAP vor Optimierungen],
  table(
    columns: 4,
    [*Service*], [*Klasse*], [*Methode*], [*#gls("CRAP")-Score*],
    [Web-UI], [Submissions.tsx], [mapConfigToDisplay], [407.1],
    [Web-UI], [Dashboard.tsx], [fetchTasks], [314.5],
    [Web-UI], [SubmissionModal.tsx], [SubmissionModal], [197.5],
    [Communication-Service], [ChatService], [getChat], [132.0],
    [Response-Service], [BedrockProxyClient], [generateReview], [132.0],
  ),
) <fig:crap_before>

Um diese identifizierten Ausreißer zu beheben, wurden durch KI unterstützte Refactoring-Maßnahmen durchgeführt. Im Backend-Bereich (z. B. im Communication-Service und Response-Service) lag der Fokus primär auf der Erhöhung der Testabdeckung durch die automatisierte Generierung von Mockito-Unit-Tests. Da die unzureichende Codeabdeckung eine zentrale Rolle in der Formel für @CRAP spielt, führte eine Erhöhung der Testabdeckung zu einer drastischen Reduktion des Indexwertes auf die zugrundeliegende zyklomatische Komplexität.

In der Web-UI wurden komplexe React-Komponenten hingegen primär strukturell zerlegt. Verschachtelte Codeblöcke und umfangreiche Logikzweige wurden in kleinere Hilfsfunktionen mit einer zyklomatischen Komplexität von maximal 5 extrahiert.

Das Ergebnis dieser Optimierungsmaßnahmen ist in @fig:crap_after dargestellt. Sämtliche zuvor kritischen Methoden konnten erfolgreich auf oder unter den festgelegten Schwellwert von 30 gesenkt werden.

#figure(
  caption: [Höchste verbleibende Werte für den Index @CRAP nach den Optimierungen],
  table(
    columns: 4,
    [*Service*], [*Klasse*], [*Methode*], [*#gls("CRAP")-Score*],
    [User-Service], [CognitoService], [searchUsers], [30.0],
    [Communication-Service], [ChatRepository], [findMessages], [30.0],
    [Response-Service], [ResultService], [isAuthorOfSubmission], [30.0],
    [Notification-Service], [NotificationSseService], [push], [20.0],
    [Web-UI / Backend], [(Alle verbleibenden)], [(Diverse)], [< 20.0],
  ),
) <fig:crap_after>

== Dokumentation <sec:documentation>
// (Claude, Matthias)
Für die Endpunkte der API liefern Spezifikationen gemäß OpenAPI @openapi_initiative_nodate umfangreiche Dokumentation. Aus diesen Spezifikationen wird durch ein Python Skript eine Kollektion an Postman @postman_website_nodate Ressourcen erstellt. Neben den eigentlichen Requests werden dabei auch Environment-Dateien generiert, welche die für die Cognito-Authentifizierung notwendigen Variablen bereitstellen. Zugangsdaten selbst werden nicht versioniert, sondern zur Laufzeit über den Postman Vault referenziert. Ergänzend existieren, analog zu der in @sec:agents-md beschriebenen `AGENTS.md`, weitere `AGENTS.md`-Dateien in einzelnen Unterverzeichnissen (z. B. im `postman`-Ordner), die den Agenten spezifische Architekturentscheidungen, Endpunkte der API, Datenbankenschemata und Beispiel-Payloads bereitstellen. Für die Visualisierung der Architektur wurde die Diagramsoftware Draw.io @drawio_website_nodate verwendet. Typst @typst_website_nodate, ein modernes, in Berlin entwickeltes Textsatzsystem, wurde genutzt, um den Projektbericht zu schreiben und in eine Datei im Format PDF zu übersetzen. Neben der zentralen `README.md` im Wurzelverzeichnis des Repositories, welche einen Überblick über das Gesamtprojekt bietet, hat die KI die einzelnen Microservices nach dem Generieren des Codes zusätzlich jeweils in einer gesonderten `README.md` im Wurzelverzeichnis des jeweiligen Microservices dokumentiert. Da diese Dokumentationsartefakte überwiegend einmalig generiert werden, besteht analog zu der bereits in @sec:agents-md beschriebenen Problematik das Risiko, dass sie bei späteren Codeänderungen nicht konsequent nachgepflegt werden und veralten.

