= Kurze Zusammenfassung

== Zusammenfassung

Im Rahmen dieser Arbeit wurde mit PeerReview ein webbasiertes System zur gegenseitigen Begutachtung wissenschaftlicher Arbeiten als @MVP realisiert. Der eigentliche Begutachtungsprozess, von der Konfiguration einer Abgabe über die Zuweisung eines Gutachters und die Einreichung der Arbeit bis zur Rückgabe des fertigen Gutachtens, wird von vier eng zusammenspielenden Kern-Services getragen, ergänzt um vier weitere Services für Kommunikation, Benachrichtigungen, Nutzerverwaltung und die Web-Oberfläche (siehe @ch:architecture). Die in der Zielsetzung geforderte Plugin-Architektur wurde im Configuration Service umgesetzt und mit acht Plugins für unterschiedliche Review-Typen und Bewertungsformate ausgestattet, sodass sich neue Begutachtungsworkflows ohne Eingriff in den Kern des Systems ergänzen lassen.

Die gesamte Infrastruktur wurde vollständig über das AWS Cloud Development Kit deklariert und automatisiert auf serverlosen, containerisierten Ressourcen bereitgestellt. Ein durchgängiges Muster über alle Services hinweg bildet dabei die konsequente Trennung von Zuständigkeiten, etwa durch das Database-per-Service-Prinzip, klar abgegrenzte Autorisierungsebenen oder austauschbare Strategie-Implementierungen wie im Notification Service. Ergänzt wurde die Entwicklung durch eine GitHub-Actions-Pipeline für Build und Deployment. Über den gesamten Entwicklungsprozess hinweg kamen zudem verschiedene agentische Coding-Werkzeuge wie Claude Code, Google Antigravity und OpenCode zum Einsatz. Deren Nutzung hatte jedoch ihren Preis, die Testabdeckung fiel zwischen den Services zunächst höchst uneinheitlich aus und blieb in Teilen, etwa in der Web-UI, zeitweise vollständig aus, weshalb sie erst nachträglich über den CRAP-Index gezielt sichtbar gemacht und manuell nachgebessert werden musste (siehe @sec:optimization). Nutzen und Grenzen des agentischen Vorgehens werden ausführlich in @ch:implementation-workflow sowie im Kapitel @ch:vibecoding-critique diskutiert.

== Fazit

Die in @sec:goals formulierten technischen Ziele wurden zu einem großen Teil erreicht. Der Begutachtungsprozess ist als Menge unabhängiger, lose gekoppelter Microservices umgesetzt, die Plugin-Architektur erlaubt die Erweiterung um neue Review-Verfahren, die Infrastruktur liegt vollständig als Code vor und ist über eine automatisierte Pipeline ausrollbar, und sämtliche Schnittstellen sind über OpenAPI dokumentiert. Das System bildet damit den in der Aufgabenstellung geforderten Kernprozess funktionsfähig ab und lässt sich, wie in @sec:optimization beschrieben, agil um weitere Funktionalität ergänzen.

Differenzierter fällt die Bewertung des übergeordneten, experimentellen Ziels aus, zu untersuchen, wie weit sich eine verteilte, sicherheitsrelevante Architektur mithilfe agentischer Coding-Werkzeuge realisieren lässt. Einerseits ermöglichte der Einsatz von Claude Code, Google Antigravity und weiteren Werkzeugen eine für ein Greenfield-Projekt dieser Größenordnung ungewöhnlich hohe Entwicklungsgeschwindigkeit und erlaubte es auch Teammitgliedern ohne tiefe AWS- oder Spring-Erfahrung, funktionsfähige Services beizutragen. Andererseits bestätigten sich über den Projektverlauf hinweg fast alle im Kapitel @ch:vibecoding-critique festgehaltenen Vorbehalte des Teams. Die bereits erwähnte, erst nachträglich über den CRAP-Index aufgedeckte Testabdeckungslücke ist dabei weniger als gewöhnliche Qualitätssicherungsmaßnahme zu verstehen, sondern als unmittelbarer Beleg dafür, dass sich die Agenten ohne wiederholte manuelle Nachsteuerung nicht durchgehend an vereinbarte Konventionen hielten. Hinzu kamen von mehreren Teammitgliedern berichtete Erfahrungen eines spürbaren Verlusts an Systemverständnis bis hin zur kognitiven Verschuldung, häufig nur halb umgesetzter Änderungen sowie ein Vorfall, bei dem übernommene Vorschläge des GitHub Copilot Reviewers die Funktionsfähigkeit des Systems zunächst brachen statt sie zu verbessern. Auch die finanzielle Dimension blieb nicht folgenlos, nach Angaben des Teams verbrauchte bereits ein einzelner Agenten-Lauf für einen Microservice mehr als die Hälfte des ursprünglich veranschlagten Projektbudgets von rund 50 \$. Insgesamt lässt sich festhalten, dass agentisches Coding im Rahmen dieses Projekts vor allem dann verlässlich funktionierte, wenn es durch klare architektonische Leitplanken wie das Monorepo, die initiale Baseline und den Template Service eingehegt sowie durch wiederholte manuelle Kontrolle begleitet wurde, während es ohne diese Kontrolle schnell zu inkonsistenten oder sogar funktionsuntüchtigen Ergebnissen führte. Für sicherheitsrelevante, verteilte Systeme erscheint es damit derzeit eher als wirkungsvoller Beschleuniger unter durchgehender menschlicher Kontrolle denn als Ersatz für diese.

== Ausblick

Fachlich wurden im Rahmen des MVP bewusst mehrere Funktionen zurückgestellt, die sich für eine Weiterentwicklung anbieten, darunter PDF-Annotationen im Browser, die Unterstützung weiterer Einreichungsformate neben PDF, ein automatisierter Erinnerungsdienst für anstehende Fristen sowie ein eigenständiger Reporting-Service für komplexere statistische Auswertungen. Auf infrastruktureller Seite wurde aus Kostengründen bislang auf eine Multi-Availability-Zone-Architektur verzichtet, ebenso auf eine dauerhafte Provisioned Concurrency für die eingesetzten Lambda-Proxies, wodurch bei geringer Last spürbare Kaltstart-Latenzen entstehen können. Für ein produktives Wachstum über den aktuellen Nutzungsumfang hinaus wäre außerdem ein Pub/Sub-Backend wie Redis erforderlich, um die aktuell instanzgebundenen Server-Sent-Events im Communication und Notification Service auch bei mehreren parallelen Task-Instanzen zuverlässig auszuliefern.

Prozessual legt die gemachte Erfahrung nahe, projektspezifische `AGENTS.md`-Dateien bereits vor dem eigentlichen Implementierungsbeginn deutlich detaillierter auszuarbeiten, statt Konventionen und Testabdeckung erst nachträglich über Maßnahmen wie die CRAP-Index-Optimierung anzugleichen. Ein solches Vorgehen könnte die im Projektverlauf beobachtete Uneinheitlichkeit zwischen den agentisch entwickelten Services von Anfang an deutlich reduzieren.
