spring.application.name=notification
spring.main.banner-mode=off
management.endpoint.health.probes.enabled=true
server.port=${SERVER_PORT:8080}

# AWS SQS Configuration
spring.cloud.aws.sqs.dualstack-enabled=true
aws.sqs.request.queue-name=${SQS_REQUEST_QUEUE:}
spring.cloud.aws.region.static=${AWS_REGION:eu-north-1}

# Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:notification}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Secrets Manager
aws.secrets.name=${SECRETS_NAME:msa26/notification/credentials}
