spring.application.name=response
spring.main.banner-mode=off
management.endpoint.health.probes.enabled=true
server.port=${SERVER_PORT:8080}

# AWS SQS Configuration
spring.cloud.aws.sqs.dualstack-enabled=true
aws.sqs.request.queue-name=${SQS_REQUEST_QUEUE:}
aws.sqs.submission-ready.queue-name=${SQS_SUBMISSION_READY_QUEUE:}
aws.sqs.notification.queue-name=${SQS_NOTIFICATION_QUEUE:}
spring.cloud.aws.region.static=${AWS_REGION:eu-north-1}

# DynamoDB Configuration
aws.dynamodb.table-name=${DYNAMODB_TABLE_NAME:response-service-results}
spring.cloud.aws.dynamodb.dualstack-enabled=true

# S3 Configuration
aws.s3.bucket-name=${S3_BUCKET_NAME:msa26-peer-review-response-documents}
aws.s3.presigned-url-expiration-minutes=15
