spring.application.name=template

# AWS SQS Configuration
aws.sqs.request.queue-name={${AWS_REQUEST_QUEUE_NAME:template-queue-request}}
aws.sqs.response.queue-name={${AWS_RESPONSE_QUEUE_NAME:template-queue-response}}

spring.cloud.aws.region.static=eu-north-1


