spring.application.name=communication
spring.main.banner-mode=off

management.endpoint.health.probes.enabled=true
server.port=${SERVER_PORT:8080}
spring.cloud.aws.region.static=${AWS_REGION}
aws.dynamodb.table-name=${DYNAMODB_TABLE_NAME:communication-service}


user.service.url=${USER_SERVICE_URL:http://user.internal.services:8081}
matching.service.url=${MATCHING_SERVICE_URL:http://matching.internal.services:8081}
workflow.service.url=${WORKFLOW_SERVICE_URL:http://workflow.internal.services:8081}
configuration.service.url=${CONFIGURATION_SERVICE_URL:http://configuration.internal.services:8080}
